// // Code generated by xgen. DO NOT EDIT.

// package schemas

// import (
// 	"encoding/xml"
// )

// // ACCCDOCComplexType ...
// type ACCCDOCComplexType struct {
// 	BCARQ  *BCARQComplexType  `xml:"BCARQ"`
// 	SISARQ *SISARQComplexType `xml:"SISARQ"`
// 	ESTARQ string             `xml:"ESTARQ"`
// }

// // SISARQComplexType is Participante
// type SISARQComplexType struct {
// 	ACCC471    *ACCC471ComplexType    `xml:"ACCC471"`
// 	ACCC471RET *ACCC471RETComplexType `xml:"ACCC471RET"`
// }

// // ACCCDOC is Destinado ao participante informar o registro de garantia na C3.
// type ACCCDOC *ACCCDOCComplexType

// // ACCC471ComplexType is Grupo de Contrato.
// type ACCC471ComplexType struct {
// 	GrupoACCC471GarSCR []*GrupoACCC471GarSCRComplexType `xml:"Grupo_ACCC471_GarSCR"`
// }

// // GrupoACCC471GarSCRComplexType is Grupo Mercadoria
// type GrupoACCC471GarSCRComplexType struct {
// 	XMLName                     xml.Name                                `xml:"Grupo_ACCC471_GarSCRComplexType"`
// 	CodErroAttr                 string                                  `xml:"CodErro,attr,omitempty"`
// 	IdentdPartAdmdo             string                                  `xml:"IdentdPartAdmdo"`
// 	NumCtrlIFGar                string                                  `xml:"NumCtrlIFGar"`
// 	TpGar                       *TpGarCodErr                            `xml:"TpGar"`
// 	TpGarSCR                    *TpGarSCRCodErr                         `xml:"TpGarSCR"`
// 	SubTpGarSCR                 *SubTpGarSCRCodErr                      `xml:"SubTpGarSCR"`
// 	SitGar                      string                                  `xml:"SitGar"`
// 	IndrBemFincd                *IndrCodErr                             `xml:"IndrBemFincd"`
// 	PercGar                     *PercentualCodErr                       `xml:"PercGar"`
// 	VlrOrGar                    *ValorCodErr                            `xml:"VlrOrGar"`
// 	VlrGarDtReaval              *ValorCodErr                            `xml:"VlrGarDtReaval"`
// 	DtReaval                    *DataCodErr                             `xml:"DtReaval"`
// 	ClassRscCesta               string                                  `xml:"ClassRscCesta"`
// 	GrupoACCC471Veic            *GrupoACCC471VeicComplexType            `xml:"Grupo_ACCC471_Veic"`
// 	GrupoACCC471Imovel          *GrupoACCC471ImovelComplexType          `xml:"Grupo_ACCC471_Imovel"`
// 	GrupoACCC471GarFidejussoria *GrupoACCC471GarFidejussoriaComplexType `xml:"Grupo_ACCC471_GarFidejussoria"`
// 	GrupoACCC471Equipmnt        *GrupoEquipmntComplexType               `xml:"Grupo_ACCC471_Equipmnt"`
// 	GrupoACCC471InstntoFinanc   *GrupoInstntoFinancComplexType          `xml:"Grupo_ACCC471_InstntoFinanc"`
// 	GrupoACCC471Mercdria        *GrupoMercdriaComplexType               `xml:"Grupo_ACCC471_Mercdria"`
// }

// // GrupoACCC471ImovelComplexType is Grupo de Endereço do Imóvel
// type GrupoACCC471ImovelComplexType struct {
// 	XMLName               xml.Name                   `xml:"Grupo_ACCC471_ImovelComplexType"`
// 	TpImovl               string                     `xml:"TpImovl"`
// 	TpUsoImovl            string                     `xml:"TpUsoImovl"`
// 	NumInscrMuncplImovl   string                     `xml:"NumInscrMuncplImovl"`
// 	NumMatriclImovl       string                     `xml:"NumMatriclImovl"`
// 	IdCartrio             string                     `xml:"IdCartrio"`
// 	GrupoACCC471EndImovel *GrupoEndImovelComplexType `xml:"Grupo_ACCC471_EndImovel"`
// }

// // GrupoRETImovelComplexType is Grupo de Endereço do Imóvel
// type GrupoRETImovelComplexType struct {
// 	CodErroAttr              string                        `xml:"CodErro,attr,omitempty"`
// 	TpImovl                  *TpImovlCodErr                `xml:"TpImovl"`
// 	TpUsoImovl               *TpUsoImovlCodErr             `xml:"TpUsoImovl"`
// 	NumInscrMuncplImovl      *NumInscrMuncplImovlCodErr    `xml:"NumInscrMuncplImovl"`
// 	NumMatriclImovl          *NumMatriclImovlCodErr        `xml:"NumMatriclImovl"`
// 	IdCartrio                *IdCartrioInstntoFinancCodErr `xml:"IdCartrio"`
// 	GrupoACCC471RETEndImovel *GrupoEndImovelComplexType    `xml:"Grupo_ACCC471RET_EndImovel"`
// }

// // GrupoACCC471GarFidejussoriaComplexType is Grupo de Endereço Garantia Fidejussória
// type GrupoACCC471GarFidejussoriaComplexType struct {
// 	XMLName                     xml.Name                                  `xml:"Grupo_ACCC471_GarFidejussoriaComplexType"`
// 	SeqGarFidjssria             int                                       `xml:"SeqGarFidjssria"`
// 	TpPessoaGarFidjssria        string                                    `xml:"TpPessoaGarFidjssria"`
// 	CNPJCPFPessoaGarFidjssria   string                                    `xml:"CNPJ_CPFPessoaGarFidjssria"`
// 	GrupoACCC471GarFidjssriaPF  *GrupoACCC471GarFidjssriaPFComplexType    `xml:"Grupo_ACCC471_GarFidjssriaPF"`
// 	GrupoACCC471GarFidjssriaPJ  *GrupoACCC471GarFidjssriaPJComplexType    `xml:"Grupo_ACCC471_GarFidjssriaPJ"`
// 	GrupoACCC471EndGarFidjssria []*GrupoACCC471EndGarFidjssriaComplexType `xml:"Grupo_ACCC471_EndGarFidjssria"`
// }

// // GrupoRETGarFidejussoriaComplexType is Grupo de Endereço Garantia Fidejussória
// type GrupoRETGarFidejussoriaComplexType struct {
// 	CodErroAttr                    string                                    `xml:"CodErro,attr,omitempty"`
// 	SeqGarFidjssria                *SeqGarFidjssriaCodErr                    `xml:"SeqGarFidjssria"`
// 	TpPessoaGarFidjssria           *TpPessoaCodErr                           `xml:"TpPessoaGarFidjssria"`
// 	CNPJCPFPessoaGarFidjssria      *CNPJCPFCodErr                            `xml:"CNPJ_CPFPessoaGarFidjssria"`
// 	GrupoACCC471RETGarFidjssriaPF  *GrupoACCC471GarFidjssriaPFComplexType    `xml:"Grupo_ACCC471RET_GarFidjssriaPF"`
// 	GrupoACCC471RETGarFidjssriaPJ  *GrupoACCC471RETGarFidjssriaPJComplexType `xml:"Grupo_ACCC471RET_GarFidjssriaPJ"`
// 	GrupoACCC471RETEndGarFidjssria []*GrupoACCC471EndGarFidjssriaComplexType `xml:"Grupo_ACCC471RET_EndGarFidjssria"`
// }

// // GrupoACCC471GarFidjssriaPJComplexType is Grupo de Representante Legal
// type GrupoACCC471GarFidjssriaPJComplexType struct {
// 	XMLName                   xml.Name                     `xml:"Grupo_ACCC471_GarFidjssriaPJComplexType"`
// 	NomEmpGarFidjssria        string                       `xml:"NomEmpGarFidjssria"`
// 	DtAbert                   string                       `xml:"DtAbert"`
// 	TelComl                   string                       `xml:"TelComl"`
// 	NomContato                string                       `xml:"NomContato"`
// 	TpCtrl                    int                          `xml:"TpCtrl"`
// 	Fatrmnt                   float64                      `xml:"Fatrmnt"`
// 	PortePessoaGarFidjssriaPJ int                          `xml:"PortePessoaGarFidjssriaPJ"`
// 	GrupoACCC471ReprLegal     []*GrupoReprLegalComplexType `xml:"Grupo_ACCC471_ReprLegal"`
// }

// // GrupoACCC471RETGarFidjssriaPJComplexType is Grupo de Representante Legal
// type GrupoACCC471RETGarFidjssriaPJComplexType struct {
// 	XMLName                   xml.Name                     `xml:"Grupo_ACCC471RET_GarFidjssriaPJComplexType"`
// 	CodErroAttr               string                       `xml:"CodErro,attr,omitempty"`
// 	NomEmpGarFidjssria        *NomeCodErr                  `xml:"NomEmpGarFidjssria"`
// 	DtAbert                   *DataCodErr                  `xml:"DtAbert"`
// 	TelComl                   *NumTelCodErr                `xml:"TelComl"`
// 	NomContato                *NomeCodErr                  `xml:"NomContato"`
// 	TpCtrl                    *TpCtrlCodErr                `xml:"TpCtrl"`
// 	Fatrmnt                   *ValorCodErr                 `xml:"Fatrmnt"`
// 	PortePessoaGarFidjssriaPJ *PorteCliCodErr              `xml:"PortePessoaGarFidjssriaPJ"`
// 	GrupoACCC471RETReprLegal  []*GrupoReprLegalComplexType `xml:"Grupo_ACCC471RET_ReprLegal"`
// }

// // GrupoACCC471GarFidjssriaPFComplexType is Número de Identificação
// type GrupoACCC471GarFidjssriaPFComplexType struct {
// 	XMLName                   xml.Name            `xml:"Grupo_ACCC471_GarFidjssriaPFComplexType"`
// 	CodErroAttr               string              `xml:"CodErro,attr,omitempty"`
// 	NomPessoaGarFidjssria     *NomeCodErr         `xml:"NomPessoaGarFidjssria"`
// 	NomMae                    *NomeCodErr         `xml:"NomMae"`
// 	EstadoCivil               *EstadoCivilCodErr  `xml:"EstadoCivil"`
// 	CPFConjuge                *CPFCodErr          `xml:"CPFConjuge"`
// 	NomConjuge                *NomeCodErr         `xml:"NomConjuge"`
// 	PortePessoaGarFidjssriaPF *PorteCliCodErr     `xml:"PortePessoaGarFidjssriaPF"`
// 	TpIdentc                  *TpIdentcCodErr     `xml:"TpIdentc"`
// 	NumIdentc                 *NumDocIdentcCodErr `xml:"NumIdentc"`
// }

// // GrupoACCC471EndGarFidjssriaComplexType is Pais Endereço Garantia Fidejussória
// type GrupoACCC471EndGarFidjssriaComplexType struct {
// 	XMLName             xml.Name      `xml:"Grupo_ACCC471_EndGarFidjssriaComplexType"`
// 	CodErroAttr         string        `xml:"CodErro,attr,omitempty"`
// 	TpEndGarFidjssria   *TpEndCodErr  `xml:"TpEndGarFidjssria"`
// 	EndGarFidjssria     *EndCodErr    `xml:"EndGarFidjssria"`
// 	CEPEndGarFidjssria  *CEPCodErr    `xml:"CEPEndGarFidjssria"`
// 	CidEndGarFidjssria  *CidadeCodErr `xml:"CidEndGarFidjssria"`
// 	UFEndGarFidjssria   *UFCodErr     `xml:"UFEndGarFidjssria"`
// 	PaisEndGarFidjssria *PaisCodErr   `xml:"PaisEndGarFidjssria"`
// }

// // GrupoInstntoFinancComplexType is Grupo de Pessoa
// type GrupoInstntoFinancComplexType struct {
// 	TpInstntoFinanc         string                      `xml:"TpInstntoFinanc"`
// 	CodInstntoFinanc        string                      `xml:"CodInstntoFinanc"`
// 	DtEmissInstntoFinanc    string                      `xml:"DtEmissInstntoFinanc"`
// 	DtinialInstntoFinanc    string                      `xml:"DtinialInstntoFinanc"`
// 	DtVencInstntoFinanc     string                      `xml:"DtVencInstntoFinanc"`
// 	QtdEmitd                int                         `xml:"QtdEmitd"`
// 	VlrUnit                 float64                     `xml:"VlrUnit"`
// 	NumMatriclInstntoFinanc string                      `xml:"NumMatriclInstntoFinanc"`
// 	IdCartrioInstntoFinanc  string                      `xml:"IdCartrioInstntoFinanc"`
// 	NumFatr                 string                      `xml:"NumFatr"`
// 	TpDuplicata             int                         `xml:"TpDuplicata"`
// 	Obs                     string                      `xml:"Obs"`
// 	ConfcActe               string                      `xml:"ConfcActe"`
// 	DtConfcActe             string                      `xml:"DtConfcActe"`
// 	VlrDesct                float64                     `xml:"VlrDesct"`
// 	DtIniDesct              string                      `xml:"DtIniDesct"`
// 	DtFimDesct              string                      `xml:"DtFimDesct"`
// 	GrupoACCC471Pessoa      []*GrupoPessoa              `xml:"Grupo_ACCC471_Pessoa"`
// 	GrupoACCC471NotaFiscal  []*NotaFiscalDupComplexType `xml:"Grupo_ACCC471_NotaFiscal"`
// 	GrupoACCC471VenctoOrdem []*VenctoOrdemComplexType   `xml:"Grupo_ACCC471_VenctoOrdem"`
// 	GrupoACCC471Boleto      []*BoletoDupComplexType     `xml:"Grupo_ACCC471_Boleto"`
// }

// // GrupoRETInstntoFinancComplexType is Grupo de Pessoa
// type GrupoRETInstntoFinancComplexType struct {
// 	CodErroAttr                string                         `xml:"CodErro,attr,omitempty"`
// 	TpInstntoFinanc            *TpInstntoFinancCodErr         `xml:"TpInstntoFinanc"`
// 	CodInstntoFinanc           *CodInstntoFinancCodErr        `xml:"CodInstntoFinanc"`
// 	DtEmissInstntoFinanc       *DataCodErr                    `xml:"DtEmissInstntoFinanc"`
// 	DtinialInstntoFinanc       *DataCodErr                    `xml:"DtinialInstntoFinanc"`
// 	DtVencInstntoFinanc        *DataCodErr                    `xml:"DtVencInstntoFinanc"`
// 	QtdEmitd                   *QtdCodErr                     `xml:"QtdEmitd"`
// 	VlrUnit                    *ValorCodErr                   `xml:"VlrUnit"`
// 	NumMatriclInstntoFinanc    *NumMatriclInstntoFinancCodErr `xml:"NumMatriclInstntoFinanc"`
// 	IdCartrioInstntoFinanc     *IdCartrioInstntoFinancCodErr  `xml:"IdCartrioInstntoFinanc"`
// 	NumFatr                    *NumFatrCodErr                 `xml:"NumFatr"`
// 	TpDuplicata                *TpDuplicataCodErr             `xml:"TpDuplicata"`
// 	Obs                        *ObsCodErr                     `xml:"Obs"`
// 	ConfcActe                  *ConfcActeCodErr               `xml:"ConfcActe"`
// 	DtConfcActe                *DataCodErr                    `xml:"DtConfcActe"`
// 	VlrDesct                   *ValorCodErr                   `xml:"VlrDesct"`
// 	DtIniDesct                 *DataCodErr                    `xml:"DtIniDesct"`
// 	DtFimDesct                 *DataCodErr                    `xml:"DtFimDesct"`
// 	GrupoACCC471RETPessoa      []*GrupoPessoaRET              `xml:"Grupo_ACCC471RET_Pessoa"`
// 	GrupoACCC471RETNotaFiscal  []*NotaFiscalDupComplexType    `xml:"Grupo_ACCC471RET_NotaFiscal"`
// 	GrupoACCC471RETVenctoOrdem []*VenctoOrdemComplexType      `xml:"Grupo_ACCC471RET_VenctoOrdem"`
// 	GrupoACCC471RETBoleto      []*BoletoDupComplexType        `xml:"Grupo_ACCC471RET_Boleto"`
// }

// // GrupoPessoa is Grupo de Endereço Pessoa
// type GrupoPessoa struct {
// 	TpPessoaInstntoFinanc      string                          `xml:"TpPessoaInstntoFinanc"`
// 	CNPJCPFPessoaInstntoFinanc string                          `xml:"CNPJ_CPFPessoaInstntoFinanc"`
// 	NomPessoaInstntoFinanc     string                          `xml:"NomPessoaInstntoFinanc"`
// 	TpPessoaVincdInstntoFinanc *TpPessoaFisicaJuridicaCodErr   `xml:"TpPessoaVincdInstntoFinanc"`
// 	InscrEstadl                string                          `xml:"InscrEstadl"`
// 	PcaPgto                    string                          `xml:"PcaPgto"`
// 	GrupoACCC471EndPessoa      []*GrupoEndPessoaDupComplexType `xml:"Grupo_ACCC471_EndPessoa"`
// }

// // GrupoPessoaRET is Grupo de Endereço Pessoa
// type GrupoPessoaRET struct {
// 	CodErroAttr                string                          `xml:"CodErro,attr,omitempty"`
// 	TpPessoaInstntoFinanc      *TpPessoaInstntoFinancCodErr    `xml:"TpPessoaInstntoFinanc"`
// 	CNPJCPFPessoaInstntoFinanc *CNPJCPFCodErr                  `xml:"CNPJ_CPFPessoaInstntoFinanc"`
// 	NomPessoaInstntoFinanc     *NomeCodErr                     `xml:"NomPessoaInstntoFinanc"`
// 	TpPessoaVincdInstntoFinanc *TpPessoaCodErr                 `xml:"TpPessoaVincdInstntoFinanc"`
// 	InscrEstadl                *InscrEstadlCodErr              `xml:"InscrEstadl"`
// 	PcaPgto                    *PcaPgtoCodErr                  `xml:"PcaPgto"`
// 	GrupoACCC471RETEndPessoa   []*GrupoEndPessoaDupComplexType `xml:"Grupo_ACCC471RET_EndPessoa"`
// }

// // GrupoMercdriaComplexType is Grupo de Endereço
// type GrupoMercdriaComplexType struct {
// 	TpProdt         string                         `xml:"TpProdt"`
// 	CodProdt        string                         `xml:"CodProdt"`
// 	DescProdt       string                         `xml:"DescProdt"`
// 	PesoLiqdProdt   float64                        `xml:"PesoLiqdProdt"`
// 	AnoSaf          string                         `xml:"AnoSaf"`
// 	QtdProdt        int                            `xml:"QtdProdt"`
// 	UniddProdt      int                            `xml:"UniddProdt"`
// 	GrupoACCC471End []*GrupoMercdriaEndComplexType `xml:"Grupo_ACCC471_End"`
// }

// // GrupoRETMercdriaComplexType is Grupo de Endereço
// type GrupoRETMercdriaComplexType struct {
// 	CodErroAttr        string                         `xml:"CodErro,attr,omitempty"`
// 	TpProdt            *TpProdtCodErr                 `xml:"TpProdt"`
// 	CodProdt           *CodProdtCodErr                `xml:"CodProdt"`
// 	DescProdt          *DescProdtCodErr               `xml:"DescProdt"`
// 	PesoLiqdProdt      *PesoCodErr                    `xml:"PesoLiqdProdt"`
// 	AnoSaf             *AnoCodErr                     `xml:"AnoSaf"`
// 	QtdProdt           *QtdCodErr                     `xml:"QtdProdt"`
// 	UniddProdt         *QtdCodErr                     `xml:"UniddProdt"`
// 	GrupoACCC471RETEnd []*GrupoMercdriaEndComplexType `xml:"Grupo_ACCC471RET_End"`
// }

// // GrupoACCC471VeicComplexType is Grupo Identificação do Veículo
// type GrupoACCC471VeicComplexType struct {
// 	XMLName                xml.Name                    `xml:"Grupo_ACCC471_VeicComplexType"`
// 	VlrEntdVeic            *ValorCodErr                `xml:"VlrEntdVeic"`
// 	IdentdChassi           *IdChassiCodErr             `xml:"IdentdChassi"`
// 	TpVeic                 int                         `xml:"TpVeic"`
// 	TpTabVeicl             string                      `xml:"TpTabVeicl"`
// 	CodTabVeicl            string                      `xml:"CodTabVeicl"`
// 	UFCodTabVeicl          string                      `xml:"UFCodTabVeicl"`
// 	IndrVeicUsado          string                      `xml:"IndrVeicUsado"`
// 	NumPlaca               string                      `xml:"NumPlaca"`
// 	UFNumPlaca             string                      `xml:"UFNumPlaca"`
// 	KM                     int                         `xml:"KM"`
// 	RENAVAM                string                      `xml:"RENAVAM"`
// 	NumNota                string                      `xml:"NumNota"`
// 	NumSerNota             string                      `xml:"NumSerNota"`
// 	VlrNota                float64                     `xml:"VlrNota"`
// 	DtEmiss                string                      `xml:"DtEmiss"`
// 	GrupoACCC471IdentcVeic *GrupoIdentcVeicComplexType `xml:"Grupo_ACCC471_IdentcVeic"`
// }

// // GrupoACCC471AvalstComplexType is CNPJ ou CPF do Avalista
// type GrupoACCC471AvalstComplexType struct {
// 	XMLName       xml.Name        `xml:"Grupo_ACCC471_AvalstComplexType"`
// 	CodErroAttr   string          `xml:"CodErro,attr,omitempty"`
// 	TpCliAvalst   *TpPessoaCodErr `xml:"TpCli_Avalst"`
// 	CNPJCPFAvalst *CNPJCPFCodErr  `xml:"CNPJ_CPF_Avalst"`
// }

// // GrupoACCC471CliPFComplexType is Porte do Cliente Pessoa Fisica
// type GrupoACCC471CliPFComplexType struct {
// 	XMLName              xml.Name               `xml:"Grupo_ACCC471_CliPFComplexType"`
// 	NomCli               string                 `xml:"NomCli"`
// 	DtNasc               string                 `xml:"DtNasc"`
// 	Sexo                 string                 `xml:"Sexo"`
// 	Nacnl                string                 `xml:"Nacnl"`
// 	TpIdentc             string                 `xml:"TpIdentc"`
// 	NumIdentc            string                 `xml:"NumIdentc"`
// 	DtIdentc             string                 `xml:"DtIdentc"`
// 	OrgaoExpddr          string                 `xml:"OrgaoExpddr"`
// 	UFOrgaoExpddr        string                 `xml:"UFOrgaoExpddr"`
// 	NomMae               string                 `xml:"NomMae"`
// 	EstadoCivil          string                 `xml:"EstadoCivil"`
// 	NomConjuge           string                 `xml:"NomConjuge"`
// 	CPFConjuge           string                 `xml:"CPFConjuge"`
// 	GrupoACCC471EndCliPF []*GrupoEndComplexType `xml:"Grupo_ACCC471_EndCliPF"`
// 	TelRes               string                 `xml:"TelRes"`
// 	TelComl              string                 `xml:"TelComl"`
// 	TelCel               string                 `xml:"TelCel"`
// 	EndEletrnc           string                 `xml:"EndEletrnc"`
// 	PorteCliPF           int                    `xml:"PorteCli_PF"`
// }

// // ACCC471RETComplexType is Grupo Contratos Recusados
// type ACCC471RETComplexType struct {
// 	GrupoGarActo   *GrupoGarActoComplexType   `xml:"Grupo_Gar_Acto"`
// 	GrupoGarRecsdo *GrupoGarRecsdoComplexType `xml:"Grupo_Gar_Recsdo"`
// }

// // GrupoGarActoComplexType is Grupo de Contratos Aceitos
// type GrupoGarActoComplexType struct {
// 	XMLName                xml.Name                             `xml:"Grupo_Gar_ActoComplexType"`
// 	GrupoACCC471RETGarActo []*GrupoACCC471RETGarActoComplexType `xml:"Grupo_ACCC471RET_GarActo"`
// }

// // GrupoACCC471RETGarActoComplexType is Situacao do Registro
// type GrupoACCC471RETGarActoComplexType struct {
// 	XMLName         xml.Name `xml:"Grupo_ACCC471RET_GarActoComplexType"`
// 	IdentdPartAdmdo string   `xml:"IdentdPartAdmdo"`
// 	NumCtrlIFGar    string   `xml:"NumCtrlIFGar"`
// 	SitRegistro     string   `xml:"SitRegistro"`
// }

// // GrupoGarRecsdoComplexType is Grupo de Garantias Recusados
// type GrupoGarRecsdoComplexType struct {
// 	XMLName                  xml.Name                            `xml:"Grupo_Gar_RecsdoComplexType"`
// 	GrupoACCC471RETGarRecsdo []*GrupoACCC471RETGarSCRComplexType `xml:"Grupo_ACCC471RET_GarRecsdo"`
// }

// // GrupoACCC471RETGarSCRComplexType is Grupo Mercadoria
// type GrupoACCC471RETGarSCRComplexType struct {
// 	XMLName                        xml.Name                            `xml:"Grupo_ACCC471RET_GarSCRComplexType"`
// 	CodErroAttr                    string                              `xml:"CodErro,attr,omitempty"`
// 	IdentdPartAdmdo                *CNPJBaseCodErr                     `xml:"IdentdPartAdmdo"`
// 	NumCtrlIFGar                   *ControleIFCCCCodErr                `xml:"NumCtrlIFGar"`
// 	TpGar                          *TpGarCodErr                        `xml:"TpGar"`
// 	TpGarSCR                       *TpGarSCRCodErr                     `xml:"TpGarSCR"`
// 	SubTpGarSCR                    *SubTpGarSCRCodErr                  `xml:"SubTpGarSCR"`
// 	SitGar                         *SitGarCodErr                       `xml:"SitGar"`
// 	IndrBemFincd                   *IndrCodErr                         `xml:"IndrBemFincd"`
// 	PercGar                        *PercentualCodErr                   `xml:"PercGar"`
// 	VlrOrGar                       *ValorCodErr                        `xml:"VlrOrGar"`
// 	VlrGarDtReaval                 *ValorCodErr                        `xml:"VlrGarDtReaval"`
// 	DtReaval                       *DataCodErr                         `xml:"DtReaval"`
// 	ClassRscCesta                  *ClassRscCestaCodErr                `xml:"ClassRscCesta"`
// 	GrupoACCC471RETVeic            *GrupoRETVeicComplexType            `xml:"Grupo_ACCC471RET_Veic"`
// 	GrupoACCC471RETImovel          *GrupoRETImovelComplexType          `xml:"Grupo_ACCC471RET_Imovel"`
// 	GrupoACCC471RETGarFidejussoria *GrupoRETGarFidejussoriaComplexType `xml:"Grupo_ACCC471RET_GarFidejussoria"`
// 	GrupoACCC471RETEquipmnt        *GrupoEquipmntComplexType           `xml:"Grupo_ACCC471RET_Equipmnt"`
// 	GrupoACCC471RETInstntoFinanc   *GrupoRETInstntoFinancComplexType   `xml:"Grupo_ACCC471RET_InstntoFinanc"`
// 	GrupoACCC471RETMercdria        *GrupoRETMercdriaComplexType        `xml:"Grupo_ACCC471RET_Mercdria"`
// }

// // GrupoRETVeicComplexType is Grupo Identificação do Veículo
// type GrupoRETVeicComplexType struct {
// 	CodErroAttr               string                      `xml:"CodErro,attr,omitempty"`
// 	VlrEntdVeic               *ValorCodErr                `xml:"VlrEntdVeic"`
// 	IdentdChassi              *IdChassiCodErr             `xml:"IdentdChassi"`
// 	TpVeic                    *TpVeiclCodErr              `xml:"TpVeic"`
// 	TpTabVeicl                *TpTabVeiclCodErr           `xml:"TpTabVeicl"`
// 	CodTabVeicl               *CodTabVeiclCodErr          `xml:"CodTabVeicl"`
// 	UFCodTabVeicl             *UFCodErr                   `xml:"UFCodTabVeicl"`
// 	IndrVeicUsado             *IndrCodErr                 `xml:"IndrVeicUsado"`
// 	NumPlaca                  *NumPlacaVeicCodErr         `xml:"NumPlaca"`
// 	UFNumPlaca                *UFCodErr                   `xml:"UFNumPlaca"`
// 	KM                        *QtdCodErr                  `xml:"KM"`
// 	RENAVAM                   *RenavamCodErr              `xml:"RENAVAM"`
// 	NumNota                   *NumNotaFiscalCodErr        `xml:"NumNota"`
// 	NumSerNota                string                      `xml:"NumSerNota"`
// 	VlrNota                   *ValorCodErr                `xml:"VlrNota"`
// 	DtEmiss                   *DataCodErr                 `xml:"DtEmiss"`
// 	GrupoACCC471RETIdentcVeic *GrupoIdentcVeicComplexType `xml:"Grupo_ACCC471RET_IdentcVeic"`
// }

package schemas