// Code generated by xgen. DO NOT EDIT.

package schemas

import (
	"encoding/xml"
	"go-xsd/internal/structs/common"
)

// ACCCDOCComplexType ...
type ACCCDOCComplexType struct {
	XMLName    xml.Name `xml:"ACCCDOC"`
	Xmlns   string         `xml:"xmlns,attr"`
	BCARQ      schemas.BCARQComplexType    `xml:"BCARQ"`
	SISARQ     SISARQComplexType   `xml:"SISARQ"`
	ESTARQ     string   `xml:"ESTARQ,omitempty"`
}

// SISARQComplexType is Participante
type SISARQComplexType struct {
	ACCC470    *ACCC470ComplexType    `xml:"ACCC470"`
	ACCC470RET *ACCC470RETComplexType `xml:"ACCC470RET"`
}

// ACCCDOC is Destinado ao particinte solicitar consulta de garantia na
//                         C3.
type ACCCDOC *ACCCDOCComplexType

// ACCC470ComplexType is Grupo Chave Duplicata.
type ACCC470ComplexType struct {
    IdentdPartAdmdo            string                                   `xml:"IdentdPartAdmdo"`
    GrupoACCC470NuGarantia     *GrupoACCC470NuGarantiaComplexType       `xml:"Grupo_ACCC470_NuGarantia_ComplexType"`  // Match the XMLName
    GrupoACCC470ChaveOrdem     []*GrupoACCC470ChaveOrdemComplexType     `xml:"Grupo_ACCC470_ChaveOrdem"`
    GrupoACCC470ChaveDuplicata []*GrupoACCC470ChaveDuplicataComplexType `xml:"Grupo_ACCC470_ChaveDuplicata"`
}

// GrupoACCC470NuGarantiaComplexType is Numero Único da Garantia na C3
type GrupoACCC470NuGarantiaComplexType struct {
	XMLName xml.Name `xml:"Grupo_ACCC470_NuGarantia_ComplexType"`
	NUGar   []string `xml:"NUGar"`
}

// GrupoACCC470ChaveOrdemComplexType is Grupo de Chave da Nota Fiscal
type GrupoACCC470ChaveOrdemComplexType struct {
	XMLName            xml.Name                       `xml:"Grupo_ACCC470_ChaveOrdemComplexType"`
	NumOrdem           string                         `xml:"NumOrdem"`
	CNPJEmit           string                         `xml:"CNPJEmit"`
	CNPJCPFSacd        string                         `xml:"CNPJ_CPFSacd"`
	DtEmiss            string                         `xml:"DtEmiss"`
	Valor              float64                        `xml:"Valor"`
	GrupoACCC470ChNota *GrupoACCC470ChNotaComplexType `xml:"Grupo_ACCC470_ChNota"`
}

// GrupoACCC470ChaveDuplicataComplexType is Valor unitario do instrumento financeiro
type GrupoACCC470ChaveDuplicataComplexType struct {
	XMLName             xml.Name `xml:"Grupo_ACCC470_ChaveDuplicataComplexType"`
	CodInstntoFinanc    string   `xml:"CodInstntoFinanc"`
	CNPJEmit            string   `xml:"CNPJEmit"`
	CNPJCPFSacd         string   `xml:"CNPJ_CPFSacd"`
	DtVencInstntoFinanc string   `xml:"DtVencInstntoFinanc"`
	VlrUnit             float64  `xml:"VlrUnit"`
}

// GrupoACCC470ChNotaComplexType is Chave da Nota Fiscal
type GrupoACCC470ChNotaComplexType struct {
	XMLName xml.Name `xml:"Grupo_ACCC470_ChNotaComplexType"`
	ChNota  string   `xml:"ChNota"`
}

// ACCC470RETComplexType is Grupo Garantias Erro
type ACCC470RETComplexType struct {
	IdentdPartAdmdo   schemas.CNPJBaseCodErr               `xml:"IdentdPartAdmdo"`
	GrupoGarExistte   *GrupoGarExistteComplexType   `xml:"Grupo_Gar_Existte"`
	GrupoGarInexistte *GrupoGarInexistteComplexType `xml:"Grupo_Gar_Inexistte"`
	GrupoGarErro      *GrupoGarExistteComplexType   `xml:"Grupo_Gar_Erro"`
}

// GrupoACCC470RETNuGarantiaComplexType is Numero Único da Garantia na C3
type GrupoACCC470RETNuGarantiaComplexType struct {
	XMLName xml.Name `xml:"Grupo_ACCC470RET_NuGarantiaComplexType"`
	NUGar   []string `xml:"NUGar"`
}

// GrupoGarExistteComplexType is Grupo Chave Duplicata
type GrupoGarExistteComplexType struct {
	XMLName                       xml.Name                                    `xml:"Grupo_Gar_ExistteComplexType"`
	GrupoACCC470RETNuGarantia     *GrupoACCC470RETNuGarantiaComplexType       `xml:"Grupo_ACCC470RET_NuGarantia"`
	GrupoACCC470RETChaveOrdem     []*GrupoACCC470RETChaveOrdemComplexType     `xml:"Grupo_ACCC470RET_ChaveOrdem"`
	GrupoACCC470RETChaveDuplicata []*GrupoACCC470RETChaveDuplicataComplexType `xml:"Grupo_ACCC470RET_ChaveDuplicata"`
}

// GrupoACCC470RETChaveOrdemComplexType is Situação de Registro
type GrupoACCC470RETChaveOrdemComplexType struct {
	XMLName     xml.Name `xml:"Grupo_ACCC470RET_ChaveOrdemComplexType"`
	NumOrdem    string   `xml:"NumOrdem"`
	CNPJEmit    string   `xml:"CNPJEmit"`
	CNPJCPFSacd string   `xml:"CNPJ_CPFSacd"`
	DtEmiss     string   `xml:"DtEmiss"`
	Valor       float64  `xml:"Valor"`
	SitRegistro string   `xml:"SitRegistro"`
}

// GrupoACCC470RETChaveDuplicataComplexType is Local do registro da duplicata (Comprometida com qual IMF)
type GrupoACCC470RETChaveDuplicataComplexType struct {
	XMLName             xml.Name                       `xml:"Grupo_ACCC470RET_ChaveDuplicataComplexType"`
	CodErroAttr         string                         `xml:"CodErro,attr,omitempty"`
	CodInstntoFinanc    schemas.CodInstntoFinancCodErr        `xml:"CodInstntoFinanc"`
	CNPJEmit            schemas.CNPJCodErr                    `xml:"CNPJEmit"`
	CNPJCPFSacd         schemas.CNPJCPFCodErr                 `xml:"CNPJ_CPFSacd"`
	DtVencInstntoFinanc schemas.DataCodErr                    `xml:"DtVencInstntoFinanc"`
	VlrUnit             schemas.ValorCodErr                   `xml:"VlrUnit"`
	GrupoACCC470ChNota  *GrupoACCC470ChNotaComplexType `xml:"Grupo_ACCC470_ChNota"`
	SitRegistro         string                         `xml:"SitRegistro"`
	SituacaoCorda       string                         `xml:"SituacaoCorda"`
	LocalRegistro       string                         `xml:"LocalRegistro"`
}

// GrupoGarInexistteComplexType is Grupo Chave Duplicata
type GrupoGarInexistteComplexType struct {
	XMLName                       xml.Name                                    `xml:"Grupo_Gar_InexistteComplexType"`
	GrupoACCC470RETNuGarantia     *GrupoACCC470RETNuGarantiaComplexType       `xml:"Grupo_ACCC470RET_NuGarantia"`
	GrupoACCC470RETChaveOrdem     []*GrupoACCC470RETChaveOrdemComplexType     `xml:"Grupo_ACCC470RET_ChaveOrdem"`
	GrupoACCC470RETChaveDuplicata []*GrupoACCC470RETChaveDuplicataComplexType `xml:"Grupo_ACCC470RET_ChaveDuplicata"`
}
