// Code generated by xgen. DO NOT EDIT.

package ACCC471ERR

import (
	common "go-xsd/internal/structs/common"
)

// ACCCDOC is Erro no arquivo de inclusão de termo.
type ACCCDOC common.ACCCDOCERRComplexType
