// Code generated by xgen. DO NOT EDIT.

package schemas

import (
	"time"
	"encoding/xml"
)

// ACCCDOCPROComplexType ...
type ACCCDOCPROComplexType struct {
	BCARQ *BCARQComplexType `xml:"BCARQ"`
}

// ACCCDOCERRComplexType ...
type ACCCDOCERRComplexType struct {
	BCARQ *BCARQERRComplexType `xml:"BCARQ"`
}

// BCARQComplexType is Data de Referência
type BCARQComplexType struct {
	NomArq           string               `xml:"NomArq"`
	NumCtrlEmis      string               `xml:"NumCtrlEmis,omitempty"`
	NumCtrlDestOr    string               `xml:"NumCtrlDestOr,omitempty"`
	ISPBEmissor      string               `xml:"ISPBEmissor"`
	ISPBDestinatario string               `xml:"ISPBDestinatario"`
	DtHrArq          string               `xml:"DtHrArq"`
	SitReq           int                  `xml:"SitReq"`
	GrupoSeq         *GrupoSeqComplexType `xml:"Grupo_Seq"`
	DtRef            string               `xml:"DtRef"`
}

// GrupoSeqComplexType is Indicador Continuidade
type GrupoSeqComplexType struct {
	XMLName  xml.Name `xml:"Grupo_Seq"`
	NumSeq   int      `xml:"NumSeq"`
	IndrCont string   `xml:"IndrCont"`
}

// BCARQERRComplexType is Nome do Arquivo
type BCARQERRComplexType struct {
	NomArq *NomArqCodErrComplexType `xml:"NomArq"`
}

// ESTARQSimpleType is Cópia do conteúdo das informacões de estímulo, quando houverem.
type ESTARQSimpleType string

// Ano is Formato: AAAA
type Ano string

// AnoCodErr is Ano com código de erro
type AnoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// AnoMes is Formato = AAAA-MM, onde AAAA é ano – MM é mês
type AnoMes string

// AnoMesCodErr is Ano e mês com código de erro
type AnoMesCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CNPJ is Número de Identificação da Pessoa Jurídica no
//                 Cadastro Nacional de Pessoa Jurídica. No caso de
//                 transferência para pessoas isentas de CNPJ,
//                 o campo CNPJ deve ser preenchido com zero.
type CNPJ string

// CNPJCodErr is Número de Identificação da Pessoa Jurídica no
//                 Cadastro Nacional de Pessoa Jurídica. No caso de
//                 transferência para pessoas isentas de CNPJ,
//                 o campo CNPJ deve ser preenchido com zero.
type CNPJCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CNPJBase is Primeiras 8 posicões do CNPJ.
type CNPJBase string

// CNPJBaseCodErr is CNPJ base com atributo para retorno de código de erro.
type CNPJBaseCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpPessoaINTCodErr is Tipo Pessoa Intermediário
type TpPessoaINTCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*TpPessoaINT
}

// TpPessoaFisicaJuridica is Tipo Pessoa Fisica / Juridica
type TpPessoaFisicaJuridica string

// TpPessoaFisicaJuridicaCodErr is Tipo Pessoa Fisica / Juridica, com campo codigo erro
type TpPessoaFisicaJuridicaCodErr struct {
	XMLName     xml.Name `xml:"TpPessoaFisica_JuridicaCodErr"`
	CodErroAttr string   `xml:"CodErro,attr,omitempty"`
	Value       string   `xml:",chardata"`
}

// TpPessoaSacdCodErr is Tipo Pessoa Sacado
type TpPessoaSacdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*TpPessoaSacd
}

// NumBcoCodErr is Número do Banco
type NumBcoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*NumBco
}

// DigtVerificdrCodErr is Digíto verificador
type DigtVerificdrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*DigtVerificdr
}

// LinhaDigitvlCodErr is Fim Grupo de Boletos
type LinhaDigitvlCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*LinhaDigitvl
}

// CNPJCPF is Número de Identificação da Pessoa Jurídica no
//                 Cadastro Nacional de Pessoa Jurídica ou o Número
//                 no Cadastro de Pessoa Física. No caso de
//                 transferência para pessoas isentas de CNPJ ou
//                 CPF, o campo CNPJ ou CPF deve ser preenchido com zero.
type CNPJCPF string

// CNPJCPFCodErr is Número de Identificacao da Pessoa Jurídica no Cadastro Nacional de Pessoa Jurídica
//                 ou o Número no Cadastro de Pessoa Física com atributo para retorno de código de erro.
type CNPJCPFCodErr struct {
	XMLName     xml.Name `xml:"CNPJ_CPFCodErr"`
	CodErroAttr string   `xml:"CodErro,attr,omitempty"`
	Value       string   `xml:",chardata"`
}

// CPF is Número no Cadastro de Pessoa Física. No caso de
//                 transferência para pessoas isentas de CNPJ ou
//                 CPF, o campo CPF deve ser preenchido com zero.
type CPF string

// CPFCodErr is Número no Cadastro de Pessoa Física. No caso de
//                 transferência para pessoas isentas de CNPJ ou
//                 CPF, o campo CPF deve ser preenchido com zero.
type CPFCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CodCatg is Código da categoria do veículo
type CodCatg string

// CodCatgCodErr is Código da categoria do veículo
type CodCatgCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CodContrtoOr is Código do contrato original, preenchidos com zeros à esquerda
type CodContrtoOr string

// CodContrtoOrCodErr is Código do contrato original com atributo para retorno de código de erro.
type CodContrtoOrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CodContrtoSCR is Código de identificação do contrato SCR
//                 Código alfanumérico interno da IF identificador do contrato.
//                 Deverá ser preenchido exatamente com o mesmo conteúdo que é informado no layout SCR 3040
type CodContrtoSCR string

// CodContrtoSCRCodErr ...
type CodContrtoSCRCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// RetenSubtlRsc is Identificador de Retenção Substancia de Risco.
//                 Deverá ser preenchido conforme o domínio “Cedente” ou “Cessionário”, obrigatório.
type RetenSubtlRsc int

// RetenSubtlRscErr ...
type RetenSubtlRscErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// CodErro is Código de erro. Vide tabela de código de erros no Manual de Leiautes.
type CodErro string

// CodInstntoFinanc is Código Instrumento Financeiro
type CodInstntoFinanc string

// CodInstntoFinancCodErr is Código Instrumento Financeiro
type CodInstntoFinancCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CodMarca is Código da marca do veículo
type CodMarca string

// CodMarcaCodErr is Código da marca do veículo
type CodMarcaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CodModl is Código da modelo do veículo
type CodModl string

// CodModlCodErr is Código da modelo do veículo
type CodModlCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CodMoedaCNAB is Código da moeda no padrão CNAB.
type CodMoedaCNAB string

// CodMoedaCNABCodErr ...
type CodMoedaCNABCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CodProdt is Código de Produto
type CodProdt string

// CodProdtCodErr is Código de Produto
type CodProdtCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CodTabVeicl is Código de Produto
type CodTabVeicl string

// CodTabVeiclCodErr is NCódigo de Produto com atributo para retorno de código de erro.
type CodTabVeiclCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// ControleIF is Número de Controle da IF
type ControleIF string

// ControleIFCodErr is Número unico de controle gerado pela IF com atributo para retorno de código de erro.
type ControleIFCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// ControleIFCCC is Número único de controle gerado pela IF, preenchidos com zeros à esquerda.
type ControleIFCCC string

// NumCtrlIFGar is Número de controle IF da garantia
type NumCtrlIFGar string

// ControleIFCCCCodErr is Número unico de controle gerado pela IF com atributo para retorno de código de erro.
type ControleIFCCCCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// Data is Data no formato AAAA-MM-DD. Onde
//                 AAAA = ano,
//                 MM = mês [01-12],
//                 DD = dia [01-31].
type Data string

// DataCodErr is Data com atributo para retorno de código de erro.
type DataCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// DataHoraCodErr is Data e hora com atributo para retorno de código de erro.
type DataHoraCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// DataHora is Data e hora no formato AAAA-MM-DDThh:mm:ss. Onde
//                 AAAA = ano,
//                 MM = mês [01-12],
//                 DD = dia [01-31],
//                 hh = horas [00-23],
//                 mm = minutos [00-59],
//                 ss = segundos [00-59].
type DataHora string

// Hora is hh = horas [00-23],
//                 mm = minutos [00-59],
//                 ss = segundos [00-59].
type Hora time.Time

// DescProdt is Descrição do Produto
type DescProdt string

// DescProdtCodErr is Descrição do Produto
type DescProdtCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// Justificativa is Justificativa
type Justificativa string

// JustificativaCodErr is Justificativa
type JustificativaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// DescCodErr is Descrição do Serviço ou Produto
type DescCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*Desc
}

// NumConsProtErr is Número de Protocolo de Consulta da Nota Fiscal Eletrônica na Serpro
type NumConsProtErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*NumConsProt
}

// DtHrConsProtErr is Data Hora da Consulta da Nota Fiscal Eletrônica na Serpro
type DtHrConsProtErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*DtHrConsProt
}

// CodConsProtErr is Código de Ocorrência da Consulta da Nota Fiscal Eletrônica na Serpro
type CodConsProtErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*CodConsProt
}

// NumOrdemCodErr is Número da Ordem
type NumOrdemCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*NumOrdem
}

// EndEletrnc is Endereço eletrônico na Internet.
type EndEletrnc string

// EndEletrncCodErr is Endereço eletrônico na Internet.
type EndEletrncCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// GrupoDadObjtoContrtoConsigdComplexType is Data de Admissão
type GrupoDadObjtoContrtoConsigdComplexType struct {
	CodErroAttr             string                    `xml:"CodErro,attr,omitempty"`
	CNPJBaseEnteCons        *CNPJBaseCodErr           `xml:"CNPJBase_EnteCons"`
	TpEnteCons              *TpEnteConsSCRCodErr      `xml:"TpEnteCons"`
	CNPJBaseOrgaoPagdr      *CNPJBaseCodErr           `xml:"CNPJBaseOrgaoPagdr"`
	CNPJOrgaoPagdrServdr    *CNPJCodErr               `xml:"CNPJOrgaoPagdrServdr"`
	IdentcOrgaoPagdr        *IdentcOrgaoPagdrCodErr   `xml:"IdentcOrgaoPagdr"`
	NUAvebcSCC              *NUCodErr                 `xml:"NUAvebcSCC"`
	NumContrtoEnteCons      *NumContrtoEnteConsCodErr `xml:"NumContrtoEnteCons"`
	NumBenfcEnteCons        *NumBenfcEnteConsCodErr   `xml:"NumBenfcEnteCons"`
	NumMatriclEnteCons      *NumMatriclEnteConsCodErr `xml:"NumMatriclEnteCons"`
	AnoMesComptcPrimroDesct *AnoMesCodErr             `xml:"AnoMesComptcPrimroDesct"`
	VlrMargConsigd          *ValorCodErr              `xml:"VlrMargConsigd"`
	TpVincEmprtcio          *TpVincEmprtcioCodErr     `xml:"TpVincEmprtcio"`
	DtAdmiss                *DataCodErr               `xml:"DtAdmiss"`
}

// GrupoEndImovelComplexType is Pais
type GrupoEndImovelComplexType struct {
	CodErroAttr string        `xml:"CodErro,attr,omitempty"`
	TpEndImovl  *TpEndCodErr  `xml:"TpEndImovl"`
	EndImovl    *EndCodErr    `xml:"EndImovl"`
	CEPImovl    *CEPCodErr    `xml:"CEPImovl"`
	CidImovl    *CidadeCodErr `xml:"CidImovl"`
	UFImovl     *UFCodErr     `xml:"UFImovl"`
	PaisImovl   *PaisCodErr   `xml:"PaisImovl"`
}

// GrupoEndCliComplexType is País
type GrupoEndCliComplexType struct {
	CodErroAttr string        `xml:"CodErro,attr,omitempty"`
	TpEnd       *TpEndCodErr  `xml:"TpEnd"`
	End         *EndCodErr    `xml:"End"`
	CEP         *CEPCodErr    `xml:"CEP"`
	Cid         *CidadeCodErr `xml:"Cid"`
	UF          *UFCodErr     `xml:"UF"`
	Pais        *PaisCodErr   `xml:"Pais"`
}

// GrupoEndGarFidjssriaComplexType is Pais Endereço Garantia Fidejussória
type GrupoEndGarFidjssriaComplexType struct {
	CodErroAttr         string        `xml:"CodErro,attr,omitempty"`
	TpEndGarFidjssria   *TpEndCodErr  `xml:"TpEndGarFidjssria"`
	EndGarFidjssria     *EndCodErr    `xml:"EndGarFidjssria"`
	CEPEndGarFidjssria  *CEPCodErr    `xml:"CEPEndGarFidjssria"`
	CidEndGarFidjssria  *CidadeCodErr `xml:"CidEndGarFidjssria"`
	UFEndGarFidjssria   *UFCodErr     `xml:"UFEndGarFidjssria"`
	PaisEndGarFidjssria *PaisCodErr   `xml:"PaisEndGarFidjssria"`
}

// GrupoReprLegalComplexType is CPF do Represente Legal
type GrupoReprLegalComplexType struct {
	CodErroAttr      string         `xml:"CodErro,attr,omitempty"`
	CNPJCPFReprLegal *CNPJCPFCodErr `xml:"CNPJ_CPF_ReprLegal"`
}

// GrupoEquipmntComplexType is Número de Serie do Equipamento
type GrupoEquipmntComplexType struct {
	CodErroAttr     string                  `xml:"CodErro,attr,omitempty"`
	TpEquipmnt      *TpEquipmntCodErr       `xml:"TpEquipmnt"`
	VlrEntdEquipmnt *ValorCodErr            `xml:"VlrEntdEquipmnt"`
	CNPJFabrcte     *CNPJCodErr             `xml:"CNPJFabrcte"`
	CNPJForndr      *CNPJCodErr             `xml:"CNPJForndr"`
	NumNota         *NumNotaFiscalCodErr    `xml:"NumNota"`
	NumSerNota      *NumSerNotaFiscalCodErr `xml:"NumSerNota"`
	VlrNota         *ValorCodErr            `xml:"VlrNota"`
	DtEmiss         *DataCodErr             `xml:"DtEmiss"`
	PaisFabrcc      *PaisCodErr             `xml:"PaisFabrcc"`
	NumSerEquipmnt  *NumSerEquipmntCodErr   `xml:"NumSerEquipmnt"`
}

// GrupoEndPessoaComplexType is País
type GrupoEndPessoaComplexType struct {
	CodErroAttr string        `xml:"CodErro,attr,omitempty"`
	TpEnd       *TpEndCodErr  `xml:"TpEnd"`
	End         *EndCodErr    `xml:"End"`
	CEP         *CEPCodErr    `xml:"CEP"`
	Cid         *CidadeCodErr `xml:"Cid"`
	UF          *UFCodErr     `xml:"UF"`
	Pais        *PaisCodErr   `xml:"Pais"`
}

// GrupoEndPessoaDupComplexType is País
type GrupoEndPessoaDupComplexType struct {
	CodErroAttr string            `xml:"CodErro,attr,omitempty"`
	TpEnd       *TpEndCodErr      `xml:"TpEnd"`
	End         *EndCodErr        `xml:"End"`
	CEP         *CEPCodErr        `xml:"CEP"`
	Cid         *CidadeCodErr     `xml:"Cid"`
	CodMunIBGE  *CodMunIBGECodErr `xml:"CodMunIBGE"`
	UF          *UFCodErr         `xml:"UF"`
	Pais        *PaisCodErr       `xml:"Pais"`
}

// GrupoGarFidjssriaPFComplexType is Número de Identificação
type GrupoGarFidjssriaPFComplexType struct {
	CodErroAttr               string              `xml:"CodErro,attr,omitempty"`
	NomPessoaGarFidjssria     string              `xml:"NomPessoaGarFidjssria"`
	NomMae                    *NomeCodErr         `xml:"NomMae"`
	EstadoCivil               *EstadoCivilCodErr  `xml:"EstadoCivil"`
	CPFConjuge                *CPFCodErr          `xml:"CPFConjuge"`
	NomConjuge                *NomeCodErr         `xml:"NomConjuge"`
	PortePessoaGarFidjssriaPF *PorteCliCodErr     `xml:"PortePessoaGarFidjssriaPF"`
	TpIdentc                  *TpIdentcCodErr     `xml:"TpIdentc"`
	NumIdentc                 *NumDocIdentcCodErr `xml:"NumIdentc"`
}

// GrupoMercdriaEndComplexType is País
type GrupoMercdriaEndComplexType struct {
	CodErroAttr string           `xml:"CodErro,attr,omitempty"`
	IdentcEnd   *IdentcEndCodErr `xml:"IdentcEnd"`
	TpEnd       *TpEndCodErr     `xml:"TpEnd"`
	End         *EndCodErr       `xml:"End"`
	CEP         *CEPCodErr       `xml:"CEP"`
	Cid         *CidadeCodErr    `xml:"Cid"`
	UF          *UFCodErr        `xml:"UF"`
	Pais        *PaisCodErr      `xml:"Pais"`
}

// GrupoPagtoParclComplexType is Indicador de Seguro Pago
type GrupoPagtoParclComplexType struct {
	CodErroAttr            string               `xml:"CodErro,attr,omitempty"`
	NumCtrlIFEvt           *ControleIFCCCCodErr `xml:"NumCtrlIFEvt"`
	NUEvt                  *NUCodErr            `xml:"NUEvt"`
	DtPagtoParcl           *DataCodErr          `xml:"DtPagtoParcl"`
	DtContb                *DataCodErr          `xml:"DtContb"`
	VlrPago                *ValorCodErr         `xml:"VlrPago"`
	VlrPrincipalPagtoParcl *ValorCodErr         `xml:"VlrPrincipalPagtoParcl"`
	VlrJurosPagtoParcl     *ValorCodErr         `xml:"VlrJurosPagtoParcl"`
	VlrJurosMoraPagtoParcl *ValorCodErr         `xml:"VlrJurosMoraPagtoParcl"`
	VlrMultaPagtoParcl     *ValorCodErr         `xml:"VlrMultaPagtoParcl"`
	VlrIOFAtrPagtoParcl    *ValorCodErr         `xml:"VlrIOFAtrPagtoParcl"`
	VlrDesctPagtoParcl     *ValorCodErr         `xml:"VlrDesctPagtoParcl"`
	VlrAbattPagtoParcl     *ValorCodErr         `xml:"VlrAbattPagtoParcl"`
	VlrDespPagtoParcl      *ValorCodErr         `xml:"VlrDespPagtoParcl"`
	IndrLiquidExtraJud     *IndrCodErr          `xml:"IndrLiquidExtraJud"`
	IndrLei                *IndrCodErr          `xml:"IndrLei"`
	VlrLei                 *ValorCodErr         `xml:"VlrLei"`
	IndrSegrPago           *IndrCodErr          `xml:"IndrSegrPago"`
}

// GrupoPagtoParclActoComplexType is Número Único do Evento na C3
type GrupoPagtoParclActoComplexType struct {
	XMLName      xml.Name             `xml:"GrupoPagtoParclActo_ComplexType"`
	NumCtrlIFEvt *ControleIFCCCCodErr `xml:"NumCtrlIFEvt"`
	NUEvt        *NUCodErr            `xml:"NUEvt"`
}

// GrupoParclPagasComplexType is Situacao do Repasse Parcela Paga
type GrupoParclPagasComplexType struct {
	XMLName              xml.Name             `xml:"Grupo_ParclPagasComplexType"`
	CodErroAttr          string               `xml:"CodErro,attr,omitempty"`
	NumCtrlIFParclIni    *ControleIFCCCCodErr `xml:"NumCtrlIFParclIni"`
	NumCtrlIFParclFim    *ControleIFCCCCodErr `xml:"NumCtrlIFParclFim"`
	TpParclParclPaga     *TpParclCodErr       `xml:"TpParclParclPaga"`
	VlrParclPaga         *ValorCodErr         `xml:"VlrParclPaga"`
	VlrPagoParclPaga     *ValorCodErr         `xml:"VlrPagoParclPaga"`
	IndrParclPagaDt      *IndrCodErr          `xml:"IndrParclPagaDt"`
	IndrParclPagaCedd    *IndrCodErr          `xml:"IndrParclPagaCedd"`
	CNPJBaseCesParclPaga *CNPJBaseCodErr      `xml:"CNPJBase_CesParclPaga"`
	SitRepParclPaga      *SitRepCodErr        `xml:"SitRepParclPaga"`
}

// SitConclcao is Situação da Conciliação SCR
type SitConclcao string

// SitConclcaoCodErr ...
type SitConclcaoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// SitNotaFiscal is Situação da Nota Fiscal
type SitNotaFiscal string

// SitNotaFiscalCodErr is Situação da Nota Fiscal com atributos CodErro (opcional)
type SitNotaFiscalCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// GrupoAltParclActoComplexType is Novo Valor Saldo Prejuízo
type GrupoAltParclActoComplexType struct {
	XMLName              xml.Name     `xml:"Grupo_AltParclActoComplexType"`
	CodErroAttr          string       `xml:"CodErro,attr,omitempty"`
	NovVlrParcl          *ValorCodErr `xml:"NovVlrParcl"`
	NovVlrPrincipalParcl *ValorCodErr `xml:"NovVlrPrincipalParcl"`
	NovVlrJurosParcl     *ValorCodErr `xml:"NovVlrJurosParcl"`
	NovVlrSldDevdrParcl  *ValorCodErr `xml:"NovVlrSldDevdrParcl"`
	NovVlrSldPrejzParcl  *ValorCodErr `xml:"NovVlrSldPrejzParcl"`
}

// GrupoParcelaComplexType is Grupo Parcela
type GrupoParcelaComplexType struct {
	CodErroAttr string      `xml:"CodErro,attr,omitempty"`
	NUParcl     []*NUCodErr `xml:"NUParcl"`
}

// GrupoIdentcVeicComplexType is Pais de Fabricação
type GrupoIdentcVeicComplexType struct {
	CodErroAttr    string           `xml:"CodErro,attr,omitempty"`
	VlrMercVeic    *ValorCodErr     `xml:"VlrMercVeic"`
	CodCatg        *CodCatgCodErr   `xml:"CodCatg"`
	CodMarca       *CodMarcaCodErr  `xml:"CodMarca"`
	CodModl        *CodModlCodErr   `xml:"CodModl"`
	AnoModlVeicl   *AnoCodErr       `xml:"AnoModlVeicl"`
	AnoFabrccVeicl *AnoCodErr       `xml:"AnoFabrccVeicl"`
	TpCombtvl      *TpCombtvlCodErr `xml:"TpCombtvl"`
	PaisFabrcc     *PaisCodErr      `xml:"PaisFabrcc"`
}

// GrupoImpEncargoComplexType is Indicador de Financiamento do Encargo
type GrupoImpEncargoComplexType struct {
	CodErroAttr        string                 `xml:"CodErro,attr,omitempty"`
	TpEncargo          *TpEncargoFinancCodErr `xml:"TpEncargo"`
	VlrEncargo         *ValorCodErr           `xml:"VlrEncargo"`
	IndrFincmntEncargo *IndrCodErr            `xml:"IndrFincmntEncargo"`
}

// GrupoIdentdContrtoComplexType is Tipo do Contrato
type GrupoIdentdContrtoComplexType struct {
	XMLName             xml.Name            `xml:"Grupo_Identd_ContrtoComplexType"`
	CodErroAttr         string              `xml:"CodErro,attr,omitempty"`
	CodContrtoOr        *CodContrtoOrCodErr `xml:"CodContrtoOr"`
	CNPJBaseIFOrContrto *CNPJBaseCodErr     `xml:"CNPJBase_IFOrContrto"`
	TpCli               *TpPessoaCodErr     `xml:"TpCli"`
	CNPJCPFCli          *CNPJCPFCodErr      `xml:"CNPJ_CPFCli"`
	TpContrto           *TpContrtoCodErr    `xml:"TpContrto"`
}

// GrupoJurosMoraContrtoComplexType is Percentual do Indexador Juros Mora
type GrupoJurosMoraContrtoComplexType struct {
	CodErroAttr        string                    `xml:"CodErro,attr,omitempty"`
	QtdDiasJurosMora   *QtdCodErr                `xml:"QtdDiasJurosMora"`
	TpCobrJurosMora    *TpCobrCodErr             `xml:"TpCobrJurosMora"`
	VlrJurosMora       *ValorCodErr              `xml:"VlrJurosMora"`
	TpCalcJurosMora    *TpCalcCodErr             `xml:"TpCalcJurosMora"`
	FormaCalcJurosMora *FormaCalcJurosMoraCodErr `xml:"FormaCalcJurosMora"`
	TaxJurosMora       *PercentualCodErr         `xml:"TaxJurosMora"`
	PeriodTaxJurosMora *PeriodicidadeCodErr      `xml:"PeriodTaxJurosMora"`
	IndxJurosMora      *IndxCodErr               `xml:"IndxJurosMora"`
	PercIndxJurosMora  *PercentualCodErr         `xml:"PercIndxJurosMora"`
}

// GrupoMultaContrtoComplexType is Indexador Multa
type GrupoMultaContrtoComplexType struct {
	CodErroAttr   string               `xml:"CodErro,attr,omitempty"`
	QtdDiasMulta  *QtdCodErr           `xml:"QtdDiasMulta"`
	TpCobrMulta   *TpCobrCodErr        `xml:"TpCobrMulta"`
	VlrMulta      *ValorCodErr         `xml:"VlrMulta"`
	BaseCalcMulta *BaseCalcMultaCodErr `xml:"BaseCalcMulta"`
	PercMulta     *PercentualCodErr    `xml:"PercMulta"`
	IndxMulta     *IndxCodErr          `xml:"IndxMulta"`
}

// GrupoIdentdContrtoOrigdrComplexType is Modalidade da Operação Contrato originador
type GrupoIdentdContrtoOrigdrComplexType struct {
	XMLName                   xml.Name            `xml:"Grupo_Identd_ContrtoOrigdrComplexType"`
	CodErroAttr               string              `xml:"CodErro,attr,omitempty"`
	CodContrtoOrigdr          *CodContrtoOrCodErr `xml:"CodContrtoOrigdr"`
	CNPJBaseIFOrContrtoOrigdr *CNPJBaseCodErr     `xml:"CNPJBase_IFOrContrtoOrigdr"`
	TpCliContrtoOrigdr        *TpPessoaCodErr     `xml:"TpCliContrtoOrigdr"`
	CNPJCPFCliContrtoOrigdr   *CNPJCPFCodErr      `xml:"CNPJ_CPFCliContrtoOrigdr"`
	ModOpContrtoOr            *ModOpCodErr        `xml:"ModOpContrtoOr"`
}

// GrupoEndComplexType is País
type GrupoEndComplexType struct {
	XMLName     xml.Name      `xml:"Grupo_EndComplexType"`
	CodErroAttr string        `xml:"CodErro,attr,omitempty"`
	TpEnd       *TpEndCodErr  `xml:"TpEnd"`
	End         *EndCodErr    `xml:"End"`
	CEP         *CEPCodErr    `xml:"CEP"`
	Cid         *CidadeCodErr `xml:"Cid"`
	UF          *UFCodErr     `xml:"UF"`
	Pais        *PaisCodErr   `xml:"Pais"`
}

// GrupoIdentdResComplexType is Número identificador da reserva
type GrupoIdentdResComplexType struct {
	XMLName      xml.Name            `xml:"Grupo_Identd_ResComplexType"`
	CodErroAttr  string              `xml:"CodErro,attr,omitempty"`
	DtOpRes      *DataCodErr         `xml:"DtOpRes"`
	CNPJBaseCed  *CNPJBaseCodErr     `xml:"CNPJBase_Ced"`
	CNPJBaseCes  *CNPJBaseCodErr     `xml:"CNPJBase_Ces"`
	NumIdentdRes *NumIdentdResCodErr `xml:"NumIdentdRes"`
}

// IdChassi is Identificador do chassi do veículo.
type IdChassi string

// IdChassiCodErr is Identificador do chassi do veículo com atributo para retorno de código de erro.
type IdChassiCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// Indr is Indicador 'Sim' ou 'Não'
type Indr string

// IndrSemDominio is Indicador 'Sim' ou 'Não' sem domínio
type IndrSemDominio string

// IdCartrioInstntoFinanc is ID Cartório Instrumento Financeiro
type IdCartrioInstntoFinanc string

// NumFatr is Número da Fatura
type NumFatr string

// NumFatrCodErr is Número da Fatura com atributo para retorno de código de erro.
type NumFatrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpDuplicata is Tipo da Duplicata
type TpDuplicata int

// TpDuplicataCodErr is Tipo da Duplicata com atributo para retorno de código de erro.
type TpDuplicataCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// Obs is Observações/Descrição (Duplicata e nota fiscal respectivamente)
type Obs string

// ObsCodErr is Observações/Descrição (Duplicata e nota fiscal respectivamente) com atributo para retorno de código de
//                 erro.
type ObsCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// ConfcActe is Confirmação do Aceite (duplicata)
type ConfcActe string

// ConfcActeCodErr is Confirmação do Aceite (duplicata) com atributo para retorno de código de erro.
type ConfcActeCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// InscrEstadl is Inscrição Estadual
type InscrEstadl string

// PcaPgto is Preça de Pagamento
type PcaPgto string

// PcaPgtoCodErr is Preça de Pagamento
type PcaPgtoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// InscrEstadlCodErr is Preça de Pagamento
type InscrEstadlCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// ChNota is Chave da Nota Fiscal
type ChNota string

// ChNotaCodErr is Preça de Pagamento
type ChNotaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumNotaCodErr is Numero da Nota
type NumNotaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*NumNota
}

// SerieNFeErr is Serie da NFe
type SerieNFeErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*SerieNFe
}

// IdCartrioInstntoFinancCodErr is ID Cartório Instrumento Financeiro
type IdCartrioInstntoFinancCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// IndrCess is Indicador de Cessão
//                 N - Não cedido
//                 C - Cedido
//                 R - Reservado
type IndrCess string

// IndrLiquidFinancCamr is Indicador 'Sim', 'Não' ou 'Parcial'
type IndrLiquidFinancCamr string

// IndrLiquidFinancCamrCodErr is Indicador 'Sim', 'Não' ou 'Parcial', com atributo para retorno de código de erro.
type IndrLiquidFinancCamrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// IndrCodErr ...
type IndrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// IndrSemDominioCodErr ...
type IndrSemDominioCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// IdentcEnd is Identificação de Endereço
type IdentcEnd string

// IdentcEndCodErr is Identificação de Endereço
type IdentcEndCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// IdentdLiqdFinanc is Identificador de liquidação financeira
type IdentdLiqdFinanc string

// IdentcOrgaoPagdr is Identificação do Órgão Pagador
type IdentcOrgaoPagdr int

// IdentcOrgaoPagdrCodErr ...
type IdentcOrgaoPagdrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// LitrlTpVeicl is Literal do Tipo de Veículo
type LitrlTpVeicl string

// LitrlTpVeiclCodErr is Literal do Tipo de Veículo com código de erro
type LitrlTpVeiclCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// Nome is Nome
type Nome string

// NomeCodErr ...
type NomeCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NomArqCodErrComplexType ...
type NomArqCodErrComplexType struct {
	XMLName     xml.Name `xml:"NomArqCodErr_ComplexType"`
	CodErroAttr string   `xml:"CodErro,attr"`
	Value       string   `xml:",chardata"`
}

// NU is Identificação única gerada pela CIP.
type NU string

// NossoNumeroBOL is “Nosso Número” do Boleto
type NossoNumeroBOL string

// NUCodErr is Identificação única gerada pela CIP com atributo para retorno de código de erro.
type NUCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NossoNumeroBOLErr is “Nosso Número” do Boleto.
type NossoNumeroBOLErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// MotvCodErr is Motivo do cancelamento para retorno de código de erro.
type MotvCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	*Motv
}

// NumBenfcEnteCons is Número do Benefício no Ente Consignante
type NumBenfcEnteCons int

// NumBenfcEnteConsCodErr is Número do Benefício no Ente Consignante com código de erro.
type NumBenfcEnteConsCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// NumContrtoEnteCons is Número do contrato no Ente consignante
type NumContrtoEnteCons string

// NumContrtoEnteConsCodErr is Número do contrato no Ente consignante com código de erro.
type NumContrtoEnteConsCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumIdentdRes is Número identificador da reserva.
type NumIdentdRes string

// NumIdentdResCodErr is Número identificador da reserva com atributo para retorno de código de erro.
type NumIdentdResCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumInscrMuncplImovl is Número Inscrição Municipal Imóvel
type NumInscrMuncplImovl string

// NumInscrMuncplImovlCodErr is Número Inscrição Municipal Imóvel
type NumInscrMuncplImovlCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumMatriclImovl is Número Matrícula Imóvel
type NumMatriclImovl string

// NumMatriclImovlCodErr is Número Matrícula Imóvel
type NumMatriclImovlCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumMatriclInstntoFinanc is Número Matrícula Instrumento Financeiro
type NumMatriclInstntoFinanc string

// NumMatriclInstntoFinancCodErr is Número Matrícula Instrumento Financeiro
type NumMatriclInstntoFinancCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumMatriclEnteCons is Número da matricula
type NumMatriclEnteCons string

// GrupoAtlzParcCedCodContrtoSCRComplexType is Código de Contrato SCR Cessão – Parcelas Cedidas
type GrupoAtlzParcCedCodContrtoSCRComplexType struct {
	CodErroAttr      string               `xml:"CodErro,attr,omitempty"`
	NUCess           *NUCodErr            `xml:"NUCess"`
	CodContrtoSCRCes *CodContrtoSCRCodErr `xml:"CodContrtoSCRCes"`
}

// NumMatriclEnteConsCodErr is Número da matricula com código de erro.
type NumMatriclEnteConsCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumNotaFiscal is Número da nota fiscal
type NumNotaFiscal string

// NumNotaFiscalCodErr is Número da nota fiscal
type NumNotaFiscalCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumSerEquipmnt is Número de Serie do Equipamento
type NumSerEquipmnt string

// NumSerEquipmntCodErr is Número de Serie do Equipamento
type NumSerEquipmntCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumSerNotaFiscal is Número de Série da Nota Fiscal
type NumSerNotaFiscal string

// NumSerNotaFiscalCodErr is Número de Série da Nota Fiscal
type NumSerNotaFiscalCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumSeq is Número sequencial que indica a ordem dos arquivos particionados.
type NumSeq int

// NumSeqCodErr is Número sequencial que indica a ordem dos arquivos particionados.
type NumSeqCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// NumSeqInf is Número sequencial.
type NumSeqInf int

// NumSeqInfCodErr ...
type NumSeqInfCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// NumPlacaVeic is Número da placa do veículo
type NumPlacaVeic string

// NumPlacaVeicCodErr is Número da placa do veículo
type NumPlacaVeicCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumTel is Número de telefone.
type NumTel string

// NumTelCodErr is Número de telefone.
type NumTelCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// Pais is País de fabricação
type Pais string

// PaisCodErr is País de fabricação
type PaisCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// Percentual is Número percentual. Até três inteiros e dois decimais.
//                 Deve ser informado o ponto como separador.
type Percentual float64

// Percentual5 is Número percentual. Até cinco inteiros e dois decimais.
//                 Deve ser informado o ponto como separador.
type Percentual5 float64

// PercentualCodErr is Percentual com atributo para retorno de código de erro.
type PercentualCodErr struct {
	CodErroAttr string  `xml:"CodErro,attr,omitempty"`
	Value       float64 `xml:",chardata"`
}

// Percentual5CodErr is Percentual com atributo para retorno de código de erro.
type Percentual5CodErr struct {
	CodErroAttr string  `xml:"CodErro,attr,omitempty"`
	Value       float64 `xml:",chardata"`
}

// PercentualCTC is Valor ou Percentual, com ponto flutuante.
//                 Para conteudo que expresse um percentual, o limite de casas decimais é 5.
//                 Para conteudo que expresse valores em moeda Real, deve ser informado somente
//                 ate a segunda casa decimal. Para conteudo que expresse quantidade de moeda
//                 estrangeira, taxas ou Indices, podem ser informadas ate 5 casas decimais.
//                 Para valores menores que zero, o valor sera precedido pelo sinal "-".
//                 Exemplo: para 20 negativo informe -20 .
//                 Deve ser informado o ponto separador caso tenha decimais.
//                 Exemplo: para R$100,00 Informe 100; para R$100,10 informe 100.1;
//                 para R$100,11 informe 100.11; para R$100,11 negativo informe -100.11;
//                 para R$10,11223 negativo informe -10.112233
type PercentualCTC float64

// Qtd is Quantidade de contratos na cessão.
type Qtd int

// Peso is Peso (deverá ser expresso em toneladas)
//                 Até 9 inteiros e 4 decimais e sinalizado.
//                 Valor deve ser positivo.
//                 Deve ser informado o ponto separador caso tenha decimais.
//                 Exemplo:
//                 para 1 Tonelada informe 1;
//                 para 2,5 Toneladas informe 2.5
type Peso float64

// QualifcCessSemFinanc is Quantidade de contratos na cessão.
type QualifcCessSemFinanc string

// QualifcCessSemFinancCodErr is Quantidade de contratos na cessão.
type QualifcCessSemFinancCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// RegmAmtzc is Regime de amortizãção
type RegmAmtzc string

// RegmAmtzcCodErr ...
type RegmAmtzcCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// Renavam is RENAVAM
type Renavam string

// RenavamCodErr is RENAVAM
type RenavamCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// ResFase is Reserva da Fase:
//                 1 = Fase I
//                 2 = Fase II
type ResFase int

// QtdCodErr is Quantidade de contratos na cessão com atributo para retorno de código de erro.
type QtdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// SeqGarFidjssria is Sequencia Garantia Fidejussória
type SeqGarFidjssria int

// SeqGarFidjssriaCodErr is Sequencia Garantia Fidejussória
type SeqGarFidjssriaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// Sit is Situação do registro
type Sit int

// SitCons is Situação da consulta
type SitCons int

// SitContrto is Situação do contrato
type SitContrto string

// SitContrtoCodErr is Situação do contrato com código de erro.
type SitContrtoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// SitContrtoGar is Situação da consulta
type SitContrtoGar string

// SitEvt is Situação
type SitEvt string

// SitEvtCodErr is Situação com código de erro.
type SitEvtCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// SitGar is Situação da a garantia
type SitGar string

// SitGarCodErr is Situação da garantia com código de erro.
type SitGarCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// SitGarAgtValiddr is Situação da garantia no agente validador
type SitGarAgtValiddr string

// SitGarAgtValiddrCodErr is Situação da garantia no agente validador com código de erro.
type SitGarAgtValiddrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// SitMenslddRecup is Situação da Mensalidade de Recuperação
type SitMenslddRecup int

// SitMenslddRecupCodErr is Situação da Mensalidade de Recuperação com código de erro.
type SitMenslddRecupCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// SitParcl is Situação da Parcela
type SitParcl int

// SitParclCodErr ...
type SitParclCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// SitPortbdd is Situação da Portabilidade
type SitPortbdd string

// SitRep is Situação do Repasse
type SitRep string

// SitRepCodErr ...
type SitRepCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// SitReq is Situação da Requisição
type SitReq int

// SitRes is Situação da reserva
type SitRes string

// SitRetContrto is Situação do retorno do contrato
type SitRetContrto int

// SitRegistro is Situação do registro da garantia
type SitRegistro string

// SituacaoCorda is Situação do registro da garantia
//                 0 - Ativo não comprometido
//                 1 - Ativo comprometido
//                 2 - Ativo já baixado em outra IMF
//                 3 - Pendente de confirmação
//                 4 - Consulta não realizada.
type SituacaoCorda string

// SitRetContrtoCodErr is Situação de Retorno do Contrato com atributo para retorno de código de erro.
type SitRetContrtoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// SitProc is Situação do processamento
type SitProc int

// LocalRegistro is Local do registro da duplicata.
type LocalRegistro string

// SitSolicitacao is Situação da solicitação
type SitSolicitacao int

// SitSolicitacaoCodErr is Situação da solicitação com atributo para retorno de código de erro.
type SitSolicitacaoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// Taxa is Taxa - 11,7 (11 inteiros, 7 decimais)
//                 utilizar ponto para separar decimais.
type Taxa float64

// TpCalc is Tipo de cálculo
type TpCalc string

// TpBaixContrto is Tipo de Baixa de Contrato
type TpBaixContrto string

// TpBaixContrtoCodErr is Tipo de Baixa de Contrato
type TpBaixContrtoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpBaixaParcl is Tipo de Baixa de Parcela
type TpBaixaParcl string

// TpBaixaParclCodErr ...
type TpBaixaParclCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpAcao is Tipo Ação Parcela e Garantia
type TpAcao string

// TpAcaoCodErr ...
type TpAcaoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpCalcCodErr is Tipo de cálculo com atributo para retorno de código de erro.
type TpCalcCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpCobr is Tipo de Cobrança
type TpCobr string

// TpCoobr is Tipo de Coobrigação
type TpCoobr string

// TpCoobrCodErr is Tipo de Coobrigação
type TpCoobrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpCombtvl is Tipo de Combustível do Veículo
type TpCombtvl string

// TpCombtvlCodErr is Tipo de Combustível do Veículo
type TpCombtvlCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpCobrCodErr is Tipo de Cobrança com atributo para retorno de código de erro.
type TpCobrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpContrto is Tipo de contrato de acordo com a dicionário de domínios
type TpContrto string

// TpContrtoCodErr is Tipo de contrato com atributo para retorno de código de erro.
type TpContrtoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpDivgte is Tipo Divergente
type TpDivgte int

// InfDivgte is Tipo Divergente
type InfDivgte int

// TpEnteCons is Tipo de Ente Consignante
type TpEnteCons int

// TpEnteConsCodErr is Tipo de Ente Consignante com atributo para retorno de código de erro.
type TpEnteConsCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// TpEnteConsSCR is Tipo de Ente Consignante
type TpEnteConsSCR string

// TpEnteConsSCRCodErr is Tipo de Ente Consignante com atributo para retorno de código de erro.
type TpEnteConsSCRCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpEquipmnt is Tipo Equipamento
type TpEquipmnt string

// TpEquipmntCodErr is Tipo Equipamento
type TpEquipmntCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpEvt is Tipo Divergente
type TpEvt string

// TpInst is Tipo de instituição do cedente/cessionário.
type TpInst string

// TpInstPart is Tipo de instituição
type TpInstPart string

// TpInstntoFinanc is Tipo de Instrumento Financeira
type TpInstntoFinanc string

// TpInstntoFinancCodErr is Tipo de Instrumento Financeira
type TpInstntoFinancCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpImovl is Tipo de Imóvel
type TpImovl string

// TpImovlCodErr is Tipo de Imóvel
type TpImovlCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpLeiaute is Tipo de Leiaute Conciliação SCR
type TpLeiaute string

// TpLeiauteCodErr ...
type TpLeiauteCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// Motv is Motivo do cancelamento
type Motv string

// TpMotv is Motivo da liquidação antecipada, representada por um tipo no dicionário de domínios
type TpMotv string

// TpMotvCodErr is Tipo do motivo da operação realizada no sistema com atributo para retorno de código de erro.
type TpMotvCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpMotvAltDadCad is Tipo Motivo Alteração de Dados Cadastrais
type TpMotvAltDadCad string

// TpMotvAltDadCadCodErr is Tipo Motivo Alteração de Dados Cadastrais
type TpMotvAltDadCadCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpPart is Tipo do Participante:
//                 1 - Principal
//                 2 - Administrado
type TpPart string

// TpParcl is Tipo da Parcela
type TpParcl string

// TpParclCodErr ...
type TpParclCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpPartResponsTarCtrapart is Tipo do Participante Responsável pela Tarifação da Contraparte.
//                 Pode ser preenchido com 1 - cedente ou 2 - cessionário.
type TpPartResponsTarCtrapart int

// TpPartResponsTarCtrapartCodErr is Tipo do Participante Responsável pela Tarifação da Contraparte com atributo para retorno de código de
//                 erro.
type TpPartResponsTarCtrapartCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// TpPessoa is Tipo de Pessoa Destinatário.
type TpPessoa string

// TpPessoaCodErr is Tipo de Pessoa com atributo para retorno de código de erro.
type TpPessoaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpPessoaInstntoFinanc is Tipo de Pessoa Instrumento Financeiro.
//                 F - Física
//                 J - JURIDICA
//                 E - EMITENTE
//                 S - SACADO_CPF
//                 C - SACADO_CNPJ
type TpPessoaInstntoFinanc string

// TpPessoaInstntoFinancCodErr is Tipo de Pessoa Instrumento Financeiro com atributo para retorno de código de erro.
type TpPessoaInstntoFinancCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpProdt is Tipo de Produto
type TpProdt string

// TpProdtCodErr is Tipo de Produto
type TpProdtCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpRecompra is Tipo de Recompra
type TpRecompra string

// TpRecompraCodErr ...
type TpRecompraCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpRep is Tipo de Repasse
type TpRep string

// TpRepCodErr ...
type TpRepCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpRes is Tipo de Reserva
type TpRes string

// TpResCodErr ...
type TpResCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpSolicitacao is Tipo de solicitação:
//                 1 - Relatório de Posição bloqueada Sintético
//                 2 - Relatório de Posição bloqueada Analítico
type TpSolicitacao int

// TpSolicitacaoCodErr is Tipo de Solicitação com atributo para retorno de código de erro.
type TpSolicitacaoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// TpSituacao is Tipo de situação:
//                 0 = Recusado,
//                 1 = Agendado.
type TpSituacao int

// TpSituacaoCodErr is Tipo de Situação com atributo para retorno de código de erro.
type TpSituacaoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// TpTabVeicl is Tipo da Tabela de Veículo
type TpTabVeicl string

// TpTabVeiclCodErr is Tipo da Tabela de Veículo com atributo para retorno de código de erro.
type TpTabVeiclCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpTaxa is Tipo da Taxa
type TpTaxa string

// TpTaxaCodErr is Tipo da Taxa com atributo para retorno de código de erro.
type TpTaxaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpUsoImovl is Tipo de Uso do Imóvel
type TpUsoImovl string

// TpUsoImovlCodErr is Tipo de Uso do Imóvel
type TpUsoImovlCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpVincEmprtcio is Tipo de Vínculo Empregatício
type TpVincEmprtcio int

// TpVincEmprtcioCodErr ...
type TpVincEmprtcioCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// TpVarcVlrFinancOp is Tipo de variação Sobre o Valor Financeiro da Operação
type TpVarcVlrFinancOp string

// TpVarcVlrFinancOpCodErr ...
type TpVarcVlrFinancOpCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpVeicl is Tipo do Veículo
type TpVeicl int

// TpVeiclCodErr is Tipo do Veículo com atributo para retorno de código de erro.
type TpVeiclCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// TpVencParcl is Tipo do Vencimento da Parcela
type TpVencParcl string

// TpVencParclCodErr ...
type TpVencParclCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpManut is Tipo de Manutenção do IPOC
type TpManut string

// TpManutCodErr is Tipo de Manutenção do IPOC com atributo para retorno de código de erro.
type TpManutCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumIPOCSCR is Número do Indicador Padronizado de Operações de Crédito SCR.
type NumIPOCSCR string

// NumIPOCSCRCodErr is Número do Indicador Padronizado de Operações de Crédito SCR com atributo para retorno de código de erro.
type NumIPOCSCRCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// FormaCalcJurosMora is Forma de cálculos juros de mora
type FormaCalcJurosMora string

// FormaCalcJurosMoraCodErr is Forma de cálculos juros de mora para retorno de código de erro.
type FormaCalcJurosMoraCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// FormaPgto is Forma de pagamento, de acordo com dicionario de dominios
type FormaPgto int

// FormaPgtoCodErr is Forma de pagamento, com atributo para retorno de código de erro.
type FormaPgtoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// Banco is Numero do Banco
type Banco int

// BaseCalcMulta is Base de cálculo da multa
type BaseCalcMulta string

// BaseCalcMultaCodErr ...
type BaseCalcMultaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// BancoCodErr is Numero do Banco, com atributo para retorno de código de erro.
type BancoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// Agencia is Numero da Agencia
type Agencia int

// AgenciaCodErr is Numero da Agencia, com atributo para retorno de código de erro.
type AgenciaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// CtBancaria is Numero da Conta Bancaria
type CtBancaria string

// CtBancariaCodErr is Numero da Conta Bancaria, com atributo para retorno de código de erro.
type CtBancariaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// Cidade is Nome da Cidade
type Cidade string

// CodMunIBGE is Código do Município IBGE
type CodMunIBGE int

// CidadeCodErr is Nome da Cidade com atributo para retorno de código de erro.
type CidadeCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CodMunIBGECodErr is Código do Município IBGE com atributo para retorno de código de erro.
type CodMunIBGECodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// ClassRscCesta is Classificação de Risco Cesta
type ClassRscCesta string

// ClassRscCestaCodErr is Classificação de Risco Cesta com atributo para retorno de código de erro.
type ClassRscCestaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CMC7 is Código magnético codificado em sete barras.
type CMC7 string

// CMC7CodErr is Código magnético, com atributo para retorno de código de erro.
type CMC7CodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// LinhaDigtvl is Número da linha digitável
type LinhaDigtvl string

// LinhaDigtvlCodErr is Número da linha digitável, com atributo para retorno de código de erro.
type LinhaDigtvlCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpEncargoFinanc is Tipo de Encargo Financeiro, de acordo com dicionario de dominios
type TpEncargoFinanc int

// TpEncargoFinancCodErr is Tipo de Encargo Financeiro, com atributo para retorno de código de erro.
type TpEncargoFinancCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// TpGar is Tipo de Garantia, de acordo com dicionario de dominios
type TpGar int

// TpGarCodErr is Tipo de Garantia, com atributo para retorno de código de erro.
type TpGarCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// TpGarSCR is Tipo de Garantia SCR, de acordo com dicionario de dominios
type TpGarSCR int

// TpGarSCRCodErr is Tipo de Garantia SCR, com atributo para retorno de código de erro.
type TpGarSCRCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// TpGarBacen is Tipo de Garantia, de acordo com dicionario de dominios
type TpGarBacen int

// TpGarBacenCodErr is Tipo de Garantia, com atributo para retorno de código de erro.
type TpGarBacenCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// SubTpGarSCR is Sub Tipo de Garantia SCR, de acordo com dicionario de dominios
type SubTpGarSCR int

// SubTpGarSCRCodErr is Sub Tipo de Garantia SCR, com atributo para retorno de código de erro.
type SubTpGarSCRCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// TpSexo is Tipo Sexo F - 'Feminino' ou M - 'Masculo'
type TpSexo string

// TpSexoCodErr is Tipo Sexo F - 'Feminino' ou M - 'Masculo'
type TpSexoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumDocIdentc is Numero de Documento de Identificacao Pessoa Fisica
type NumDocIdentc string

// NumDocIdentcCodErr ...
type NumDocIdentcCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// EstadoCivil is Estado Civil
type EstadoCivil string

// EstadoCivilCodErr ...
type EstadoCivilCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// End is Endereco
type End string

// EndCodErr ...
type EndCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CaracEspecial is Característica especial
type CaracEspecial string

// CaracEspecialCodErr ...
type CaracEspecialCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CaracEspecialBacen is Característica especial
type CaracEspecialBacen string

// CaracEspecialBacenCodErr ...
type CaracEspecialBacenCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CEP is Código de Endereçamento Postal
type CEP string

// CEPCodErr ...
type CEPCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// Periodicidade is Periodicidade
type Periodicidade string

// PeriodicidadeCodErr is Periodicidade com código de erro
type PeriodicidadeCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// PorteCli is Porte do Cliente
type PorteCli int

// PorteCliCodErr ...
type PorteCliCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// Indx is Indexador, de acordo com o dicionario de dominios
type Indx string

// IndxCodErr is Indexador, com atributo para retorno de código de erro.
type IndxCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// MesAno is Mes e Ano Formato = MM-AAAA, onde: MM é mês - AAAA é ano
type MesAno string

// MesAnoCodErr is Mes e Ano com código de erro
type MesAnoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// ModOp is Modalidade de Operação
type ModOp string

// ModOpCodErr is Modalidade de Operação
type ModOpCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// MtvCanceltPortldd is Motivo do cancelamento da portabilidade
//                 Conforme dicionário de domínios
type MtvCanceltPortldd string

// MtvRetenContrto is Motivo da retenção da portabilidade
//                 Conforme dicionário de domínios
type MtvRetenContrto int

// MtvDevLiquidPortldd is Motivo da devolução da portabilidade
//                 Conforme dicionário de domínios
type MtvDevLiquidPortldd int

// Nacnl is Nacionalidade
type Nacnl string

// NacnlCodErr ...
type NacnlCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NatuOp is Natureza da Operacao, de acordo com dicionario de dominios
type NatuOp int

// NatuOpCodErr is Natureza da Operacao, com código de erro.
type NatuOpCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// OrgaoExpddr is Código do Orgao Expedidor
type OrgaoExpddr string

// OrgaoExpddrCodErr is Codigo do Orgao Expedidor, com atributo para retorno de código de erro.
type OrgaoExpddrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// SitEftcPortldd is Situação da efetivação da portabilidade
//                 Conforme dicionário de domínios
type SitEftcPortldd string

// TpEnd is Tipo de Endereco, de acordo com dicionario de dominios
type TpEnd string

// TpEndCodErr is Tipo de Endereco, com atributo para retorno de código de erro.
type TpEndCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpIdentc is Tipo de Identificacao - Dicionario de dominios, 01-RG, 02-CPF, 03-CNH, etc.
type TpIdentc string

// TpIdentcCodErr is Tipo de Identificacao - Dicionario de dominios, 01-RG, 02-CPF, 03-CNH, etc.
type TpIdentcCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpCtrl is Tipo de Controle
type TpCtrl int

// TpCtrlCodErr ...
type TpCtrlCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// TpSolctcRel is Tipo de Solicitacao do Relatorio, de acordo com dicionario de dominios
type TpSolctcRel string

// TpSolctcRelCodErr is Tipo de Solicitacao de Relatorio, com atributo para retorno de código de erro.
type TpSolctcRelCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// UF is Sigla da Unidade de Federacao
type UF string

// UFCodErr is Sigla da Unidade de Federacao, com o codigo de erro.
type UFCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// Valor is Valor. Até dezessete inteiros e dois decimais e sinalizado.
//                 Para valores menores que zero, o valor será precedido pelo sinal '-'.
//                 Exemplo: para 20 negativo informe -20 .
//                 Deve ser informado o ponto separador caso tenha decimais.
//                 Exemplo: para R$100,00 informe 100; para R$100,10 informe 100.1;
//                 para R$100,11 informe 100.11; para R$100,11 negativo informe -100.11
type Valor float64

// ValorCodErr is Valor com atributo para retorno de código de erro.
type ValorCodErr struct {
	CodErroAttr string  `xml:"CodErro,attr,omitempty"`
	Value       float64 `xml:",chardata"`
}

// PesoCodErr is Peso com atributo para retorno de código de erro.
type PesoCodErr struct {
	CodErroAttr string  `xml:"CodErro,attr,omitempty"`
	Value       float64 `xml:",chardata"`
}

// NotaFiscalComplexType is Descrição do Serviço ou Produto
type NotaFiscalComplexType struct {
	CodErroAttr     string              `xml:"CodErro,attr,omitempty"`
	ChNota          *ChNotaCodErr       `xml:"ChNota"`
	NumNota         *NumNotaCodErr      `xml:"NumNota"`
	DtHrEmiss       *DataHoraCodErr     `xml:"DtHrEmiss"`
	DtVenc          *DataCodErr         `xml:"DtVenc"`
	CNPJEmit        *CNPJCodErr         `xml:"CNPJEmit"`
	InscrEstadlEmit *InscrEstadlCodErr  `xml:"InscrEstadlEmit"`
	CNPJCPFSacd     *CNPJCPFCodErr      `xml:"CNPJ_CPFSacd"`
	TpPessoaSacd    *TpPessoaSacdCodErr `xml:"TpPessoaSacd"`
	CNPJCPFINT      *CNPJCPFCodErr      `xml:"CNPJ_CPFINT"`
	TpPessoaINT     *TpPessoaINTCodErr  `xml:"TpPessoaINT"`
	Valor           *ValorCodErr        `xml:"Valor"`
	Desc            *DescCodErr         `xml:"Desc"`
}

// NotaFiscalDupComplexType is Código de Ocorrência da Consulta da Nota Fiscal Eletrônica na Serpro
type NotaFiscalDupComplexType struct {
	CodErroAttr     string                        `xml:"CodErro,attr,omitempty"`
	ChNota          *ChNotaCodErr                 `xml:"ChNota"`
	NumNota         *NumNotaFiscalCodErr          `xml:"NumNota"`
	SerieNFe        *SerieNFeErr                  `xml:"SerieNFe"`
	DtHrEmiss       *DataHoraCodErr               `xml:"DtHrEmiss"`
	DtVenc          *DataCodErr                   `xml:"DtVenc"`
	CNPJEmit        *CNPJCodErr                   `xml:"CNPJEmit"`
	InscrEstadlEmit *InscrEstadlCodErr            `xml:"InscrEstadlEmit"`
	CNPJCPFSacd     *CNPJCPFCodErr                `xml:"CNPJ_CPFSacd"`
	TpPessoaSacd    *TpPessoaFisicaJuridicaCodErr `xml:"TpPessoaSacd"`
	CNPJCPFINT      *CNPJCPFCodErr                `xml:"CNPJ_CPFINT"`
	TpPessoaINT     *TpPessoaFisicaJuridicaCodErr `xml:"TpPessoaINT"`
	Valor           *ValorCodErr                  `xml:"Valor"`
	Desc            *DescCodErr                   `xml:"Desc"`
	NumConsProt     *NumConsProtErr               `xml:"NumConsProt"`
	DtHrConsProt    *DtHrConsProtErr              `xml:"DtHrConsProt"`
	CodConsProt     *CodConsProtErr               `xml:"CodConsProt"`
}

// Desc is Descrição
type Desc string

// NumConsProt is Descrição
type NumConsProt int

// DtHrConsProt is Data e hora no formato AAAA-MM-DDThh:mm:ss. Onde
//                 AAAA = ano,
//                 MM = mês [01-12],
//                 DD = dia [01-31],
//                 hh = horas [00-23],
//                 mm = minutos [00-59],
//                 ss = segundos [00-59].
type DtHrConsProt string

// CodConsProt is Código de Ocorrência da Consulta da Nota Fiscal Eletrônica na Serpro
type CodConsProt string

// TpPessoaSacd is Tipo Pessoa Sacado
type TpPessoaSacd string

// TpPessoaINT is Tipo Pessoa Intermediário
type TpPessoaINT string

// NumNota is Número da Nota
type NumNota string

// SerieNFe is Série da NF-e
type SerieNFe string

// NumOrdem is Número da Ordem
type NumOrdem string

// VenctoOrdemComplexType is Valor da Ordem
type VenctoOrdemComplexType struct {
	CodErroAttr string          `xml:"CodErro,attr,omitempty"`
	NumOrdem    *NumOrdemCodErr `xml:"NumOrdem"`
	DtVencto    *DataCodErr     `xml:"DtVencto"`
	VlrOrdem    *ValorCodErr    `xml:"VlrOrdem"`
}

// BoletoComplexType is Valor do Boleto
type BoletoComplexType struct {
	CodErroAttr      string               `xml:"CodErro,attr,omitempty"`
	IDCIPBoleto      *NUCodErr            `xml:"IDCIPBoleto"`
	IDINSTIFGeradora *NUCodErr            `xml:"IDINSTIFGeradora"`
	NumBco           *NumBcoCodErr        `xml:"NumBco"`
	DigtVerificdr    *DigtVerificdrCodErr `xml:"DigtVerificdr"`
	LinhaDigitvl     *LinhaDigitvlCodErr  `xml:"LinhaDigitvl"`
	DtVenct          *DataCodErr          `xml:"DtVenct"`
	Valor            *ValorCodErr         `xml:"Valor"`
	AgCod            *AgCodCodErr         `xml:"AgCod"`
}

// BoletoDupComplexType is Valor do Boleto
type BoletoDupComplexType struct {
	CodErroAttr      string               `xml:"CodErro,attr,omitempty"`
	IDCIPBoleto      *NUCodErr            `xml:"IDCIPBoleto"`
	NossoNumeroBOL   *NossoNumeroBOLErr   `xml:"NossoNumeroBOL"`
	NumOrdem         *NumOrdemCodErr      `xml:"NumOrdem"`
	IDINSTIFGeradora *NUCodErr            `xml:"IDINSTIFGeradora"`
	NumBco           *NumBcoCodErr        `xml:"NumBco"`
	DigtVerificdr    *DigtVerificdrCodErr `xml:"DigtVerificdr"`
	LinhaDigitvl     *LinhaDigitvlCodErr  `xml:"LinhaDigitvl"`
	DtVenct          *DataCodErr          `xml:"DtVenct"`
	Valor            *ValorCodErr         `xml:"Valor"`
	AgCod            *AgCodCodErr         `xml:"AgCod"`
}

// AgCod is Agencia/código Beneficiario (boleto)
type AgCod string

// AgCodCodErr is Agencia/código Beneficiario (boleto)
type AgCodCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// LinhaDigitvl is Fim Grupo de Boletos
type LinhaDigitvl string

// DigtVerificdr is Digíto verificador
type DigtVerificdr string

// NumBco is Número do Banco
type NumBco string

// NUSolctcLiquidCIP is Número único de solicitação de liquidação CIP
type NUSolctcLiquidCIP string

// NUSolctcLiquidCIPCodErr is Número único de solicitação de liquidação operação CIP
type NUSolctcLiquidCIPCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// SitSolctcLiquid is Situação da solicitação de liquidação
type SitSolctcLiquid string

// NUSolctcLiquidOpCip is Número único de solicitação de liquidação operação CIP
type NUSolctcLiquidOpCip string

// NUSolctcLiquidOpCipCodErr is Número único de solicitação de liquidação operação CIP
type NUSolctcLiquidOpCipCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// SitSolctcLiquidOp is Situação da solicitação de liquidação da operação
type SitSolctcLiquidOp string

// TpAtivoLiquid is Tipo do ativo a liquidar
type TpAtivoLiquid string

// TpLanc is Tipo de Lançamento
type TpLanc string

// CodAtivo is Situação da solicitação de liquidação da operação
type CodAtivo string

// Nom is Nome
type Nom string

// NumCotas is Número de Cotas
type NumCotas string

// VlrTotLiqdar is Até quinze inteiros e dois decimais e sinalizado.
//                 Para valores menores que zero, o valor será precedido pelo sinal "-".
//                 Exemplo: para 20 negativo informe -20.
//                 Deve ser informado o ponto separador caso tenha decimais.
//                 Exemplo: para R$100,00 Informe 100;
//                 para R$100,10 informe 100.1;
//                 para R$100,11 informe 100.11;
//                 para R$100,11 negativo informe -100.11.
type VlrTotLiqdar float64

// NumCtrlIMFParcr is Número de controle da IMF Parceira
type NumCtrlIMFParcr string

// NumCtrlOpIMFParcr is Número de identificação Operação Financeira
type NumCtrlOpIMFParcr string

// NUCtrlCIP is Número único de solicitação de liquidação CIP
type NUCtrlCIP string

// QtdCotas is Quantidade de contratos na cessão.
type QtdCotas string

// IdentdPartPrincipalCodErr is Identificador do participante principal para retorno de código de erro.
type IdentdPartPrincipalCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// IdentdPartAdmdoCodErr is Identificador do participante administrado para retorno de código de erro.
type IdentdPartAdmdoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CNPJIMFParcrCodErr is CNPJ Completo da IMF Parceira para retorno de código de erro.
type CNPJIMFParcrCodErr struct {
	XMLName     xml.Name `xml:"CNPJ_IMFParcrCodErr"`
	CodErroAttr string   `xml:"CodErro,attr,omitempty"`
	Value       string   `xml:",chardata"`
}

// DtMovtoCodErr is Data movimento para retorno de código de erro.
type DtMovtoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumCtrlIMFParcrCodErr is Número de controle da IMF Parceira para retorno de código de erro.
type NumCtrlIMFParcrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpAtivoLiquidCodErr is Tipo do ativo a liquidar para retorno de código de erro.
type TpAtivoLiquidCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpLancCodErr is Tipo de Lançamento para retorno de código de erro.
type TpLancCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CodAtivoCodErr is Código do Ativo financeira para retorno de código de erro.
type CodAtivoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpPessoaEmissorTitCodErr is Tipo Pessoa Emissor título para retorno de código de erro.
type TpPessoaEmissorTitCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CNPJCPFEmissorTitCodErr is CPF/CNPJ Emissor título para retorno de código de erro.
type CNPJCPFEmissorTitCodErr struct {
	XMLName     xml.Name `xml:"CNPJ_CPFEmissorTitCodErr"`
	CodErroAttr string   `xml:"CodErro,attr,omitempty"`
	Value       string   `xml:",chardata"`
}

// NomEmissorTitCodErr is Nome Emissor título para retorno de código de erro.
type NomEmissorTitCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// NumCotasCodErr is Número de Cotas para retorno de código de erro.
type NumCotasCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// VlrTotLiqdarCodErr is Valor Total a Liquidar (Reais) para retorno de código de erro.
type VlrTotLiqdarCodErr struct {
	CodErroAttr string  `xml:"CodErro,attr,omitempty"`
	Value       float64 `xml:",chardata"`
}

// TpPessoaLancDebtdCodErr is Tipo de Pessoa a ser debitada para retorno de código de erro.
type TpPessoaLancDebtdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CNPJCPFLancDebtdCodErr is CPF/CNPJ a ser debitado para retorno de código de erro.
type CNPJCPFLancDebtdCodErr struct {
	XMLName     xml.Name `xml:"CNPJ_CPFLancDebtdCodErr"`
	CodErroAttr string   `xml:"CodErro,attr,omitempty"`
	Value       string   `xml:",chardata"`
}

// NomLancDebtdCodErr is Nome da pessoa a ser debitada para retorno de código de erro.
type NomLancDebtdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// ISPBIFDebtdCodErr is ISPB da IF a ser debitado para retorno de código de erro.
type ISPBIFDebtdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// AgLancDebtdCodErr is Número da Agência lançamento a ser debitada para retorno de código de erro.
type AgLancDebtdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// CtLancDebtdCodErr is Número da Conta lançamento a ser debitada para retorno de código de erro.
type CtLancDebtdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpPessoaLancCredtdCodErr is Tipo de Pessoa a ser creditada para retorno de código de erro.
type TpPessoaLancCredtdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CNPJCPFLancCredtdCodErr is CPF/CNPJ a ser creditado para retorno de código de erro.
type CNPJCPFLancCredtdCodErr struct {
	XMLName     xml.Name `xml:"CNPJ_CPFLancCredtdCodErr"`
	CodErroAttr string   `xml:"CodErro,attr,omitempty"`
	Value       string   `xml:",chardata"`
}

// NomLancCredtdCodErr is Nome da pessoa a ser creditada para retorno de código de erro.
type NomLancCredtdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// ISPBIFCredtdCodErr is ISPB da IF a ser creditado para retorno de código de erro.
type ISPBIFCredtdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// AgLancCredtdCodErr is Número da Agência lançamento a ser creditada para retorno de código de erro.
type AgLancCredtdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       int    `xml:",chardata"`
}

// CtLancCredtdCodErr is Número da Conta lançamento a ser creditada para retorno de código de erro.
type CtLancCredtdCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// QtdCotasCodErr is Quantidade de Cotas para retorno de código de erro.
type QtdCotasCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// VlrTotLiqdarGrupoCodErr is Valor Total a Liquidar no Grupo para retorno de código de erro.
type VlrTotLiqdarGrupoCodErr struct {
	CodErroAttr string  `xml:"CodErro,attr,omitempty"`
	Value       float64 `xml:",chardata"`
}

// NumCtrlOpIMFParcrCodErr is Número de controle da operação da IMF Parceira para retorno de código de erro.
type NumCtrlOpIMFParcrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// SitLiquidOp is Situação da liquidação da operação
type SitLiquidOp string

// VerfcIdentdd is Verificação de Identidade de um contrato.
type VerfcIdentdd string

// CanContr is Canal de contratação.
type CanContr string

// Device is Device usado para contratação
type Device string

// Ip is Ip referente ao device usado para contratação
type Ip string

// Porta is Porta referente ao Ip do device usado para contratação
type Porta string

// LatLong is Latitude ou longitudereferente ao device usado para contratação
type LatLong string

// HashDocOr is Hash do documento original.
type HashDocOr string

// HashDocAssinado is Hash do documento assinado.
type HashDocAssinado string

// TpFormalizContrto is Tipo de formalização de contrato.
type TpFormalizContrto string

// Cosif is Conta(s) Cosif (nível 5) onde é (são) contabilizada(s) a operação de crédito.
//                 Se a operação é contabilizada em várias contas então encaminhar todas as contas separadas por ponto e
//                 vírgula (;)
type Cosif string

// CdCli is Identificação do cliente (CPF, CNPJ de 8 dígitos ou outro código que defina o cliente caso não seja PF
//                 ou PJ)
type CdCli string

// VerfcIdentddCodErr ...
type VerfcIdentddCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// CanContrCodErr ...
type CanContrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// DeviceCodErr ...
type DeviceCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// IpCodErr ...
type IpCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// PortaCodErr ...
type PortaCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// LatLongCodErr ...
type LatLongCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// HashDocOrCodErr ...
type HashDocOrCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// HashDocAssinadoCodErr ...
type HashDocAssinadoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// TpFormalizContrtoCodErr ...
type TpFormalizContrtoCodErr struct {
	CodErroAttr string `xml:"CodErro,attr,omitempty"`
	Value       string `xml:",chardata"`
}

// GrupoGeoLoclcDispositComplexType is Longitude
type GrupoGeoLoclcDispositComplexType struct {
	XMLName xml.Name `xml:"Grupo_GeoLoclc_DispositComplexType"`
	Device  string   `xml:"Device"`
	Ip      string   `xml:"Ip"`
	Porta   string   `xml:"Porta"`
	Lat     string   `xml:"Lat"`
	Long    string   `xml:"Long"`
}

// GrupoDossieprobatComplexType is Hash do documento assinado
type GrupoDossieprobatComplexType struct {
	XMLName         xml.Name `xml:"Grupo_Dossie_probatComplexType"`
	DtHrCriacAlt    string   `xml:"DtHrCriacAlt"`
	HashDocOr       string   `xml:"HashDocOr"`
	DtHrAssinatura  string   `xml:"DtHrAssinatura"`
	HashDocAssinado string   `xml:"HashDocAssinado"`
}

// GrupoRETGeoLoclcDispositComplexType is Longitude
type GrupoRETGeoLoclcDispositComplexType struct {
	XMLName     xml.Name       `xml:"GrupoRET_GeoLoclc_DispositComplexType"`
	CodErroAttr string         `xml:"CodErro,attr,omitempty"`
	Device      *DeviceCodErr  `xml:"Device"`
	Ip          *IpCodErr      `xml:"Ip"`
	Porta       *PortaCodErr   `xml:"Porta"`
	Lat         *LatLongCodErr `xml:"Lat"`
	Long        *LatLongCodErr `xml:"Long"`
}

// GrupoRETDossieprobatComplexType is Hash do documento assinado
type GrupoRETDossieprobatComplexType struct {
	XMLName         xml.Name               `xml:"GrupoRET_Dossie_probatComplexType"`
	CodErroAttr     string                 `xml:"CodErro,attr,omitempty"`
	DtHrCriacAlt    *DataHoraCodErr        `xml:"DtHrCriacAlt"`
	HashDocOr       *HashDocOrCodErr       `xml:"HashDocOr"`
	DtHrAssinatura  *DataHoraCodErr        `xml:"DtHrAssinatura"`
	HashDocAssinado *HashDocAssinadoCodErr `xml:"HashDocAssinado"`
}
